#ifndef OCU_VERSION_H_INCLUDED
#define OCU_VERSION_H_INCLUDED

/** \brief AUTOSAR Ocu Driver
 **
 ** This file contains the declaration of the version of the AUTOSAR module OCU.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */

/*==================[inclusions]============================================*/
#include <Ocu_Cfg.h>     /* Generated OCU driver config */

/*==================[macros]================================================*/

/*------------------[AUTOSAR specification version identification]----------*/
#if (defined OCU_AR_RELEASE_MAJOR_VERSION) /* to prevent double declaration */
#error OCU_AR_RELEASE_MAJOR_VERSION already defined
#endif /* if (defined OCU_AR_RELEASE_MAJOR_VERSION) */

/** AUTOSAR specification major version */
#define OCU_AR_RELEASE_MAJOR_VERSION 4U

#if (defined OCU_AR_RELEASE_MINOR_VERSION) /* to prevent double declaration */
#error OCU_AR_RELEASE_MINOR_VERSION already defined
#endif /* if (defined OCU_AR_RELEASE_MINOR_VERSION) */

/** AUTOSAR specification minor version */
#define OCU_AR_RELEASE_MINOR_VERSION 2U

#if (defined OCU_AR_RELEASE_REVISION_VERSION) /* to prevent double declaration */
#error OCU_AR_RELEASE_REVISION_VERSION already defined
#endif /* if (defined OCU_AR_RELEASE_REVISION_VERSION) */

/** AUTOSAR specification patch version */
#define OCU_AR_RELEASE_REVISION_VERSION 2U

/** AUTOSAR module ID of the OCU driver module */
#define OCU_MODULE_ID 125U

/*------------------[Cypress module version identification]----------------*/
#if (defined OCU_SW_MAJOR_VERSION) /* to prevent double declaration */
#error OCU_SW_MAJOR_VERSION already defined
#endif /* if (defined OCU_SW_MAJOR_VERSION) */

/** Driver implementation major version */
#define OCU_SW_MAJOR_VERSION 1U

#if (defined OCU_SW_MINOR_VERSION) /* to prevent double declaration */
#error OCU_SW_MINOR_VERSION already defined
#endif /* if (defined OCU_SW_MINOR_VERSION) */

/** Driver implementation minor version */
#define OCU_SW_MINOR_VERSION 10U

#if (defined OCU_SW_PATCH_VERSION) /* to prevent double declaration */
#error OCU_SW_PATCH_VERSION already defined
#endif /* if (defined OCU_SW_PATCH_VERSION) */

/** Driver implementation patch version */
#define OCU_SW_PATCH_VERSION OCU_GEN_SW_PATCH_VERSION

/** AUTOSAR vendor ID of Cypress */
#define OCU_VENDOR_ID 66U

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

#endif /*!defined(OCU_VERSION_H_INCLUDED)*/
/*==================[end of file]===========================================*/
