#ifndef ICU_RESOURCE_H
#define ICU_RESOURCE_H
/** \file Icu_Resource.h
 ** \brief AUTOSAR Icu ICU Driver
 **
 ** This file defines interfaces of register access function.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */
/*==================[inclusions]=============================================*/
#include <Icu_Defines.h>
#include <Icu_Types.h>
#include <Icu_Resource_Gpio.h>
#include <Icu_Resource_Tcpwm.h>
/*==================[macros]=================================================*/

/*==================[type definitions]=======================================*/

/*==================[external function declarations]=========================*/

#define ICU_START_SEC_CODE_ASIL_B
#include <Icu_MemMap.h>

/** \brief Icu_Gpio_GetFuncTable
 **
 ** This function gets the address of the functional table of GPIO in register layer.
 **
 **
 ** \param[in] None.
 **
 ** \return    Return the pointer to Icu_drvFctTable_t.
 ** */
extern FUNC_P2CONST(Icu_drvFctTable_t, ICU_APPL_CONST, ICU_CODE) Icu_Gpio_GetFuncTable(void);
/** \brief Icu_Tcpwm_GetFuncTable
 **
 ** This function gets the address of the functional table of TCPWM in register layer.
 **
 **
 ** \param[in] None.
 **
 ** \return    Return the pointer to Icu_drvFctTable_t.
 ** */
extern FUNC_P2CONST(Icu_drvFctTable_t, ICU_APPL_CONST, ICU_CODE) Icu_Tcpwm_GetFuncTable(void);

#define ICU_STOP_SEC_CODE_ASIL_B
#include <Icu_MemMap.h>
/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/
#endif
/*==================[end of file]============================================*/
