/** \brief AUTOSAR Adc Driver
 **
 ** This file contains the declaration of the version of the AUTOSAR module Adc.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */

#ifndef ADC_VERSION_H_INCLUDED
#define ADC_VERSION_H_INCLUDED

/*==================[inclusions]============================================*/
#include <Adc_Cfg.h>     /* Generated ADC driver config */

/*==================[macros]================================================*/

/*------------------[AUTOSAR module identification]--------------------------*/

#ifdef ADC_MODULE_ID /* to prevent double declaration */
#  error ADC_MODULE_ID already defined
#else
#  define ADC_MODULE_ID 123U
#endif /* ifdef ADC_MODULE_ID) */

/*------------------[AUTOSAR vendor identification]--------------------------*/

#ifdef ADC_VENDOR_ID /* to prevent double declaration */
#  error ADC_VENDOR_ID is already defined
#else
#  define ADC_VENDOR_ID  66U
#endif /* ifdef ADC_VENDOR_ID */

#ifdef ADC_INSTANCE_ID /* to prevent double declaration */
#  error ADC_INSTANCE_ID is already defined
#else
#  define ADC_INSTANCE_ID 0U
#endif /* ifdef ADC_VENDOR_ID */

/*------------------[AUTOSAR specification version]--------------------------*/

#if (defined ADC_AR_RELEASE_MAJOR_VERSION) /* to prevent double declaration */
#  error ADC_AR_RELEASE_MAJOR_VERSION already defined
#else
#  define ADC_AR_RELEASE_MAJOR_VERSION 4U
#endif /* if (defined ADC_AR_RELEASE_MAJOR_VERSION) */


#if (defined ADC_AR_RELEASE_MINOR_VERSION) /* to prevent double declaration */
#  error ADC_AR_RELEASE_MINOR_VERSION already defined
#else
#  define ADC_AR_RELEASE_MINOR_VERSION 2U
#endif /* if (defined ADC_AR_RELEASE_MINOR_VERSION) */


#if (defined ADC_AR_RELEASE_REVISION_VERSION) /* to prevent double declaration */
#error ADC_AR_RELEASE_REVISION_VERSION already defined
#else
#  define ADC_AR_RELEASE_REVISION_VERSION 2U
#endif /* if (defined ADC_AR_RELEASE_REVISION_VERSION) */

/*------------------[AUTOSAR module version identification]------------------*/

#if (defined ADC_SW_MAJOR_VERSION) /* to prevent double declaration */
#  error ADC_SW_MAJOR_VERSION already defined
#else
#  define ADC_SW_MAJOR_VERSION  1U
#endif /* if (defined ADC_SW_MAJOR_VERSION) */

#if (defined ADC_SW_MINOR_VERSION) /* to prevent double declaration */
#  error ADC_SW_MINOR_VERSION already defined
#else
#  define ADC_SW_MINOR_VERSION  14U
#endif /* if (defined ADC_SW_MINOR_VERSION) */

#if (defined ADC_SW_PATCH_VERSION) /* to prevent double declaration */
#  error ADC_SW_PATCH_VERSION already defined
#else
#  define ADC_SW_PATCH_VERSION  ADC_GEN_SW_PATCH_VERSION
#endif /* if (defined ADC_SW_PATCH_VERSION) */

/*------------------[AUTOSAR module version identification]------------------*/
/**
 * Macro for checking the consistency of AUTOSAR specification versions of the different files of
 * MODULE module
 */
 
/* Deviation from MISRA-C:2004 rule 19.7, MISRA-C:2012 Dir-4.9
   Justification: In case of using in Preprocessing, function-like macro is used. 
                  It improves readability. */
/* PRQA S 3453 6 */
#define ADC_AR_VERSION_CHECK( file_ar_major_version, file_ar_minor_version, file_ar_patch_version ) \
        (                                                                                           \
          (( ADC_AR_RELEASE_MAJOR_VERSION ) == ( file_ar_major_version )) &&                        \
          (( ADC_AR_RELEASE_MINOR_VERSION ) == ( file_ar_minor_version )) &&                        \
          (( ADC_AR_RELEASE_REVISION_VERSION ) == ( file_ar_patch_version ))                        \
        )

/**
 * Macro for checking the consistency of the software versions of the different files of the
 * ADC module
 */

/* Deviation from MISRA-C:2004 rule 19.7, MISRA-C:2012 Dir-4.9
   Justification: In case of using in Preprocessing, function-like macro is used. 
                  It improves readability. */
/* PRQA S 3453 6 */
#define ADC_SW_VERSION_CHECK( file_sw_major_version, file_sw_minor_version, file_sw_patch_version ) \
        (                                                                                           \
          (( ADC_SW_MAJOR_VERSION ) == ( file_sw_major_version )) &&                                \
          (( ADC_SW_MINOR_VERSION ) == ( file_sw_minor_version )) &&                                \
          (( ADC_SW_PATCH_VERSION ) >= 0)                                                           \
        )

/**
 * Macro for checking additional module related settings like module id and vendor id.
 * \pre: ADC_MODULE_ID and ADC_VENDOR_ID needs to be defined
 */
/* Deviation from MISRA-C:2004 rule 19.7, MISRA-C:2012 Dir-4.9
   Justification: In case of using in Preprocessing, function-like macro is used. 
                  It improves readability. */
/* PRQA S 3453 5 */
#define ADC_EXTRA_CHECK( module_id, vendor_id )     \
        (                                           \
          (( ADC_MODULE_ID ) == ( module_id )) &&   \
          (( ADC_VENDOR_ID ) == ( vendor_id ))      \
        )

/*==================[type definitions]=======================================*/

/*==================[external function declarations]=========================*/

/*==================[internal function declarations]=========================*/

/*==================[external constants]=====================================*/

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/

#endif /*!defined(ADC_VERSION_H_INCLUDED)*/

/*==================[end of file]============================================*/
