/** \brief AUTOSAR SPI Driver
 **
 ** This file declares the Spi Sequence functions.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */

#ifndef SPI_SEQUENCE_H_INCLUDED
#define SPI_SEQUENCE_H_INCLUDED

/*==================[inclusions]============================================*/
#include <Std_Types.h>
#include <Spi_Internal_Types.h>

/*==================[macros]================================================*/

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

#define SPI_START_SEC_CODE_ASIL_B
 #include <Spi_MemMap.h>

/** \brief Spi_Seq_HandlerJobFinished
 **
 ** Handle the specified sequence when Job has been finished.
 **
 ** \return SPI_OK    : Finished the specified Sequence transmission.
 **         SPI_NOT_OK: Not finished the specified Sequence transmission.
 **
 ** \param [in]  Sequence      Id of Sequence.
 ** \param [in]  EventStatus   Event status (passed or failed).
 ** \param [out] NextJobPtr    Pointer to Next transmit Job.
 **
 */
extern FUNC( Spi_ReturnType, SPI_CODE ) Spi_Seq_HandlerJobFinished
(
  VAR( Spi_SequenceType, AUTOMATIC ) Sequence,
  VAR( uint8, AUTOMATIC ) EventStatus,
  P2VAR( Spi_JobType, AUTOMATIC, AUTOMATIC ) NextJobPtr
);

/** \brief Spi_Seq_GetCurrentJob
 **
 ** Returns the currently transmitting job in the specified sequence.
 **
 ** \return Id of Job.
 ** \param [in] Sequence   Id of Sequence.
 **
 */
extern FUNC( Spi_JobType, SPI_CODE ) Spi_Seq_GetCurrentJob
(
  VAR( Spi_SequenceType, AUTOMATIC ) Sequence
);

/** \brief Spi_Seq_SetSequenceResult
 **
 ** Sets the sequence result.
 **
 ** \return None.
 ** \param [in] Sequence   Id of Sequence.
 ** \param [in] SeqResult   Result of the Sequence transmission.
 **
 */
extern FUNC( void, SPI_CODE) Spi_Seq_SetSequenceResult
(
  VAR( Spi_SequenceType, AUTOMATIC ) Sequence,
  VAR( Spi_SeqResultType, AUTOMATIC ) SeqResult
);

/** \brief Spi_Seq_InitAllSequences
 **
 ** Initializes the all Sequences.
 **
 ** \return None.
 **
 */
extern FUNC( void, SPI_CODE ) Spi_Seq_InitAllSequences(void);

/** \brief Spi_Seq_GetSequenceResult
 **
 ** Returns result of specified sequence.
 **
 ** \return Result of Sequence.
 ** \param [in] Sequence   Id of Sequence.
 **
 */
extern FUNC( Spi_SeqResultType, SPI_CODE ) Spi_Seq_GetSequenceResult
(
  VAR( Spi_SequenceType, AUTOMATIC ) Sequence
);

/** \brief Spi_Seq_SetJobIndex
 **
 ** Sets the job index number in sequence.
 **
 ** \return None.
 ** \param [in] Sequence   Id of Sequence.
 ** \param [in] JobIndex   Index of job in the relevant sequence.
 **
 */
extern FUNC( void, SPI_CODE ) Spi_Seq_SetJobIndex
(
  VAR( Spi_SequenceType, AUTOMATIC ) Sequence,
  VAR( Spi_JobIndexType, AUTOMATIC ) JobIndex
);

/** \brief Spi_Seq_SetAllJobIsQueued
 **
 ** Sets queued status for all jobs in the relevant sequence.
 **
 ** \return None.
 ** \param [in] Sequence   Id of Sequence.
 ** \param [in] IsQueue    Determines whether job is queued or not.
 **
 */
extern FUNC( void, SPI_CODE ) Spi_Seq_SetAllJobIsQueued
(
  VAR( Spi_SequenceType, AUTOMATIC ) Sequence,
  VAR( boolean, TYPEDEF ) IsQueue
);

#define SPI_STOP_SEC_CODE_ASIL_B
#include <Spi_MemMap.h>

/*==================[internal constants]====================================*/

/*==================[internal data]=========================================*/

#endif /*!defined(SPI_SEQUENCE_H_INCLUDED)*/

/*==================[end of file]===========================================*/
