@echo OFF

SET GEN_OPTION=%1
IF NOT "-O" == "%GEN_OPTION:~0,2%" GOTO SET_GEN_BASIC
GOTO GEN_BASIC_CONFIG_NOT_EXIST

:SET_GEN_BASIC
SET GEN_BASIC=%GEN_OPTION:~1%
echo Set generator path : %GEN_BASIC%
SHIFT

:PROCESS
SET GEN_PATH=%~dp0
SET OUT_PATH=%~f2
SET JAVA_HOME=%GEN_BASIC%\jre1.8.0_121\bin
SET GEN_HOME=%GEN_BASIC%\ComXf_1.0.13\ComXfGen\
SET PATH_BACKUP=%PATH%
SET PATH=%JAVA_HOME%
SET PRJ_DIR=%OUT_PATH%\..\..
SHIFT
SHIFT
SHIFT

IF NOT EXIST %GEN_HOME% GOTO GEN_HOME_NOT_EXIST 
IF NOT EXIST %JAVA_HOME% GOTO JAVA_HOME_NOT_EXIST 

:BEGIN
IF "" == "%0" GOTO END
SET INPUT_FILE_PATH=%INPUT_FILE_PATH% "%~f0"
SHIFT
GOTO BEGIN
:END

SET VMARGS= -vmargs -Xms256m -Xmx1024m 

"%GEN_HOME%ComXfGenC.exe" -out "%OUT_PATH%" -msn Xfrm -generate -input_files %INPUT_FILE_PATH% %VMARGS%

IF NOT "%ERRORLEVEL%" == "0" GOTO ERROR

GOTO FINISH

:GEN_BASIC_CONFIG_NOT_EXIST
echo ERR_COMXF_0037 : 'Transformer Generator Path' in SCons.arxml or 'TransformerGenerator' in SConstruct file should be configured.
GOTO ERROR

:GEN_HOME_NOT_EXIST
echo GEN_HOME = %GEN_HOME%
echo ERR_COMXF_0038 : GEN_HOME is not exist.
GOTO ERROR

:JAVA_HOME_NOT_EXIST
echo JAVA_HOME = %JAVA_HOME%
echo ERR_COMXF_0039: JAVA_HOME path is not exist.
GOTO ERROR

:ERROR
EXIT 1
GOTO FINISH

:FINISH
rmdir /s/q %PRJ_DIR%\workspace
SET PATH=%PATH_BACKUP%
@echo end