#if !defined( FLS_CHECK_H )
#define FLS_CHECK_H

/** \brief AUTOSAR Fls Flash Driver
 **
 ** This file contains version check of the AUTOSAR module Fls.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */

/*==================[inclusions]============================================*/

/*==================[macros]================================================*/

/*------------------[AUTOSAR specification version identification check]----*/

#if (!defined FLS_AR_RELEASE_MAJOR_VERSION) /* configuration check */
#error FLS_AR_RELEASE_MAJOR_VERSION must be defined
#endif /* if (!defined FLS_AR_RELEASE_MAJOR_VERSION) */

#if (!defined FLS_AR_RELEASE_MINOR_VERSION) /* configuration check */
#error FLS_AR_RELEASE_MINOR_VERSION must be defined
#endif /* if (!defined FLS_AR_RELEASE_MINOR_VERSION) */

#if (!defined FLS_AR_RELEASE_REVISION_VERSION) /* configuration check */
#error FLS_AR_RELEASE_REVISION_VERSION must be defined
#endif /* if (!defined FLS_AR_RELEASE_REVISION_VERSION) */

#if !FLS_AR_VERSION_CHECK( 4, \
                           2, \
                           2)
#error AUTOSAR AR version number mismatch
#endif

/*------------------[AUTOSAR module version identification check]-----------*/

#if (!defined FLS_SW_MAJOR_VERSION) /* configuration check */
#error FLS_SW_MAJOR_VERSION must be defined
#endif /* if (!defined FLS_SW_MAJOR_VERSION) */

#if (!defined FLS_SW_MINOR_VERSION) /* configuration check */
#error FLS_SW_MINOR_VERSION must be defined
#endif /* if (!defined FLS_SW_MINOR_VERSION) */

#if (!defined FLS_SW_PATCH_VERSION) /* configuration check */
#error FLS_SW_PATCH_VERSION must be defined
#endif /* if (!defined FLS_SW_PATCH_VERSION) */

#if !FLS_SW_VERSION_CHECK( 1, \
                           17, \
                           0) /* To avoid checking patch version, 3rd parameter is 0. */
#error AUTOSAR SW version number mismatch
#endif

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

/*==================[internal function declarations]========================*/

/*==================[external constants]====================================*/

/*==================[internal constants]====================================*/

/*==================[external data]=========================================*/

/*==================[internal data]=========================================*/

/*==================[external function definitions]=========================*/

/*==================[internal function definitions]=========================*/

#endif /* if !defined( FLS_CHECK_H ) */
/*==================[end of file]===========================================*/
