/** \brief AUTOSAR Fls Flash Driver
 **
 ** This file contains the implementation of the AUTOSAR module Fls
 ** internal data.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */

/*==================[inclusions]============================================*/

#include <Fls_LibInterface.h>   /* Library interface header file */
#include <Fls_InternalLib.h>    /* Module internal API */

/*==================[macros]================================================*/

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

/*==================[internal function declarations]========================*/

/*==================[external constants]====================================*/

/*==================[internal constants]====================================*/

/*==================[external data]=========================================*/

#define FLS_START_SEC_VAR_INIT_UNSPECIFIED
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/** \brief flash driver state */
VAR( MemIf_StatusType, FLS_VAR_INIT ) Fls_DriverState = MEMIF_UNINIT;

#define FLS_STOP_SEC_VAR_INIT_UNSPECIFIED
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

#define FLS_START_SEC_VAR_NO_INIT_UNSPECIFIED
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/** \brief job result of last job */
VAR( MemIf_JobResultType, FLS_VAR_NO_INIT ) Fls_JobResult;

/** \brief current flash mode */
VAR( MemIf_ModeType, FLS_VAR_NO_INIT ) Fls_Mode;

/** \brief holds data for the current job */
VAR( Fls_JobRequestType, FLS_VAR_NO_INIT ) Fls_JobRequest;

/** \brief holds data for verifing job */
VAR( Fls_WriteJobType, FLS_VAR_NO_INIT ) Fls_WriteGlobalJob;

/** \brief holds saved data for the suspended job */
VAR( Fls_JobRequestType, FLS_VAR_NO_INIT ) Fls_SuspendedJobRequest;

/** \brief holds saved data for suspended verifying job */
VAR( Fls_WriteJobType, FLS_VAR_NO_INIT ) Fls_WriteGlobalSuspendedJob;

/** \brief holds fault information */
VAR( Fls_FaultType, FLS_VAR_NO_INIT ) Fls_Fault;

/** \brief current cycle mode */
VAR( MemIf_ModeType, FLS_VAR_NO_INIT ) Fls_CycleMode;

/** \brief IPC structure for FLASH management API */
VAR( uint32, FLS_VAR_NO_INIT ) Fls_FMAPIIpcStruct;

/** \brief flash interface status register address */
volatile P2VAR( uint32, AUTOMATIC, FLS_APPL_DATA ) Fls_FlashStatusAddr;

/** \brief mask for reading safety mechanism IPC DATA0 register */
volatile VAR( uint32, FLS_VAR_NO_INIT ) Fls_EmbeddedListenMask;

#define FLS_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/*==================[internal data]=========================================*/

/*==================[external function definitions]=========================*/

/*==================[internal function definitions]=========================*/

/*==================[end of file]===========================================*/
