/** \brief Icu_Version.h
 **
 ** This file contains the declaration of the version of the AUTOSAR module
 ** Icu.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */

#ifndef ICU_VERSION_H_INCLUDED
#define ICU_VERSION_H_INCLUDED

/*==================[inclusions]============================================*/
#include <Icu_Cfg.h>

/*==================[macros]================================================*/

/*------------------[AUTOSAR specification version]--------------------------*/
#if (defined ICU_AR_RELEASE_MAJOR_VERSION) /* To prevent double declaration */
#error ICU_AR_RELEASE_MAJOR_VERSION already defined
#endif /* if (defined ICU_AR_RELEASE_MAJOR_VERSION) */

/* AUTOSAR specification major version. */
#define ICU_AR_RELEASE_MAJOR_VERSION 4U

#if (defined ICU_AR_RELEASE_MINOR_VERSION) /* To prevent double declaration */
#error ICU_AR_RELEASE_MINOR_VERSION already defined
#endif /* if (defined ICU_AR_RELEASE_MINOR_VERSION) */

/* AUTOSAR specification minor version. */
#define ICU_AR_RELEASE_MINOR_VERSION 2U

#if (defined ICU_AR_RELEASE_REVISION_VERSION) /* To prevent double declaration */
#error ICU_AR_RELEASE_REVISION_VERSION already defined
#endif /* if (defined ICU_AR_RELEASE_REVISION_VERSION) */

/* AUTOSAR specification revision version. */
#define ICU_AR_RELEASE_REVISION_VERSION 2U

/*------------------[AUTOSAR module identification]--------------------------*/

#if (defined ICU_MODULE_ID) /* To prevent double declaration */
#error ICU_MODULE_ID already defined
#endif /* if (defined ICU_MODULE_ID) */

/** \brief AUTOSAR module identification. */
#define ICU_MODULE_ID 122U

#if (defined ICU_INSTANCE_ID) /* to prevent double declaration */
#error ICU_INSTANCE_ID already defined
#endif /* if (defined ICU_INSTANCE_ID) */

/** \brief AUTOSAR module identification. */
#define ICU_INSTANCE_ID 0u

/*------------------[AUTOSAR module version identification]------------------*/
#if (defined ICU_SW_MAJOR_VERSION) /* To prevent double declaration */
#error ICU_SW_MAJOR_VERSION already defined
#endif /* if (defined ICU_SW_MAJOR_VERSION) */

/** \brief AUTOSAR module major version. */
#define ICU_SW_MAJOR_VERSION  1U

#if (defined ICU_SW_MINOR_VERSION) /* To prevent double declaration */
#error ICU_SW_MINOR_VERSION already defined
#endif /* if (defined ICU_SW_MINOR_VERSION) */

/** \brief AUTOSAR module minor version. */
#define ICU_SW_MINOR_VERSION  16U

#if (defined ICU_SW_PATCH_VERSION) /* To prevent double declaration */
#error ICU_SW_PATCH_VERSION already defined
#endif /* if (defined ICU_SW_PATCH_VERSION) */

/** \brief AUTOSAR module patch version. */
#define ICU_SW_PATCH_VERSION  ICU_GEN_SW_PATCH_VERSION

/*------------------[AUTOSAR vendor identification]--------------------------*/

#if (defined ICU_VENDOR_ID) /* To prevent double declaration */
#error ICU_VENDOR_ID is already defined
#endif /* if (defined ICU_VENDOR_ID) */

/** \brief AUTOSAR vendor identification. */
#define ICU_VENDOR_ID 66U

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

#endif /*!defined(ICU_VERSION_H_INCLUDED)*/

/*==================[end of file]===========================================*/
