/** \brief Lin.c
 **
 ** Library-interface: state interface ncp.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */

/*==================[inclusions]============================================*/
#include "Lin_Defines.h"

#include "Lin_LIf_State_Ncp.h"

/*==================[macros]================================================*/

/*==================[type definitions]======================================*/

/*==================[internal function declarations]========================*/

/*==================[internal data]=========================================*/

#define LIN_START_SEC_VAR_NO_INIT_ASIL_B_UNSPECIFIED
#include "Lin_MemMap.h"

/* Deviation from MISRA-C:2004 rule 8.7:, MISRA-C:2012 Rule-8.9
   Justification: Allow memory mapping (MemMap). */
/* PRQA S 3218 1 */
static VAR(Lin_VarChType, AUTOMATIC) Lin_VarCh[LIN_NUMBER_OF_CONFIGURED_CHANNELS]; 

#define LIN_STOP_SEC_VAR_NO_INIT_ASIL_B_UNSPECIFIED
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1
   Justification: MemMap.h must be included in-line. */
/* PRQA S 5087 1 */
#include "Lin_MemMap.h"

/*==================[external function definitions]=========================*/

#define LIN_START_SEC_CODE_ASIL_B
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1
   Justification: MemMap.h must be included in-line. */
/* PRQA S 5087 1 */
#include "Lin_MemMap.h"

/** \brief Lin_VarChGet
 **
 ** Internal function: obtain the channel specific variables.
 **
 ** \return Channel specific variables.
 ** \param [in] ChannelIndex   channel index
 **
 */
FUNC_P2VAR(Lin_VarChType, AUTOMATIC, AUTOMATIC) Lin_VarChGet
(
  VAR(uint8, AUTOMATIC) ChannelIndex
){
    return &(Lin_VarCh[ChannelIndex]);
}

#define LIN_STOP_SEC_CODE_ASIL_B
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1
   Justification: MemMap.h must be included in-line. */
/* PRQA S 5087 1 */
#include "Lin_MemMap.h"

/*==================[end of file]===========================================*/
