/** \brief AUTOSAR SPI Driver
 **
 ** This file contains implementation of the Spi Channel functions.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */

/*==================[inclusions]============================================*/

#include <Spi_Channel.h>
#include <Spi_Common.h>
#include <Spi_Hw.h>

/*==================[macros]================================================*/

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

/*==================[internal function declarations]========================*/

/*==================[external constants]====================================*/

/*==================[internal constants]====================================*/

/*==================[external data]=========================================*/

/*==================[internal data]=========================================*/

/*==================[external function definitions]=========================*/

#define SPI_START_SEC_CODE_ASIL_B

#include <Spi_MemMap.h>

/** \brief Spi_Chan_InitAllChannels
 **
 ** Initializes all Channels.
 **
 ** \return None.
 **
 */
FUNC( void, SPI_CODE ) Spi_Chan_InitAllChannels(void)
{
  VAR( Spi_ChannelIndexType, AUTOMATIC ) ChannelIndex;
  P2VAR( Spi_ChannelInfoType, AUTOMATIC, AUTOMATIC ) ChannelInfoPtr;
  P2CONST( Spi_ChannelConfigType, AUTOMATIC, AUTOMATIC ) ChannelConfigPtr;

  /* iterate to initialize all channels */  
  for ( ChannelIndex = 0U; ChannelIndex < Spi_Current_ConfigPtr->ChannelCount; ChannelIndex++ )
  {
    /* initialize a channel */

    /* helpers to avoid too many lookups */
    ChannelInfoPtr = ( Spi_ChannelInfoType * ) &( Spi_Info.ChannelInfoListPtr[ChannelIndex] );
    ChannelConfigPtr = &( Spi_Current_ConfigPtr->ChannelConfigListPtr[ChannelIndex] );

    /* set members of channel information to initial values */
    ChannelInfoPtr->RxBufferPtr = ChannelConfigPtr->DefaultRxBufferPtr;
    ChannelInfoPtr->TxBufferPtr = ChannelConfigPtr->DefaultTxBufferPtr;
    /* check if the relevant channel uses external buffer */
    if ( ChannelConfigPtr->ChannelType == SPI_CHANNEL_TYPE_EB )
    {
      /* set the number of bytes per data element as default */
      ChannelInfoPtr->BufferSize = 1U;
    }
    else
    {
      ChannelInfoPtr->BufferSize = ChannelConfigPtr->BufferSize;
      /* For IB channels, setup descriptors */
      Spi_Hw_UpdateDescriptor(ChannelIndex,
                              ChannelConfigPtr->DefaultTxBufferPtr,
                              ChannelConfigPtr->DefaultRxBufferPtr,
                              ChannelConfigPtr->BufferSize);
    }

    /* reset buffer positions. */
    ChannelInfoPtr->BufferPosStoredForSend = 0U;
    ChannelInfoPtr->BufferPosReceived = 0U;
  }
}

/** \brief Spi_Chan_SetupEB
 **
 ** Sets the buffers and the length of data for the EB channel.
 **
 ** \return None.
 **
 ** \param [in] Channel
 **                 Channel ID
 ** \param [in] SrcDataBufferPtr
 **                 Pointer to source data buffer
 ** \param [in] DesDataBufferPtr
 **                 Pointer to destination data buffer in RAM
 ** \param [in] Length
 **                 Length (in number of data elements) of the data to be 
 **                 transmitted from SrcdataBufferPtr and/or received 
 **                 from DesDataBufferPtr.
 **                 Min.: 1
 **                 Max.: Maximum of data specified at configuration
 **                       for this channel
 **
 */
FUNC( void, SPI_CODE ) Spi_Chan_SetupEB
(
  VAR( Spi_ChannelType, AUTOMATIC ) Channel,
  P2CONST( Spi_DataBufferType, AUTOMATIC, AUTOMATIC ) SrcDataBufferPtr,
  P2VAR( Spi_DataBufferType, AUTOMATIC, AUTOMATIC ) DesDataBufferPtr,
  VAR( Spi_NumberOfDataType, AUTOMATIC ) Length
)
{
  P2VAR( Spi_ChannelInfoType , AUTOMATIC, AUTOMATIC ) CurChannelInfoPtr;

  /* get a pointer for the relevant channel information */
  CurChannelInfoPtr = &( Spi_Info.ChannelInfoListPtr[Channel] );

  /* set current channel information */
  CurChannelInfoPtr->RxBufferPtr = DesDataBufferPtr;
  /* Deviation from MISRA-C:2004 Rule 11.5, MISRA-C:2012 Rule-11.8.
     Justification: Cast is necessary for writing to the buffer 
     in other case. */
  /* PRQA S 311 1 */
  CurChannelInfoPtr->TxBufferPtr = ( Spi_DataBufferType * ) SrcDataBufferPtr;
  CurChannelInfoPtr->BufferSize  = Length;

  /* reset buffer positions. */
  Spi_Info.ChannelInfoListPtr[Channel].BufferPosStoredForSend = 0U;
  Spi_Info.ChannelInfoListPtr[Channel].BufferPosReceived = 0U;
  
  /* update  Descriptor */
  Spi_Hw_UpdateDescriptor( Channel, SrcDataBufferPtr, DesDataBufferPtr, Length );
}

#define SPI_STOP_SEC_CODE_ASIL_B
/* Deviation from MISRA-C:2004 Rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: Spi_MemMap.h must be included in-line. */
/* PRQA S 5087 1 */
#include <Spi_MemMap.h>

/*==================[internal function definitions]=========================*/

/*==================[end of file]===========================================*/
