/** \brief AUTOSAR Fee Flash EEPROM Emulation
 **
 ** This file contains the implementation of the AUTOSAR module Fee.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-FEE42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
*/

/*****************************************************************************/
/* Include files                                                             */
/*****************************************************************************/
#include "Fee_Internal.h"

/*****************************************************************************/
/* Local pre-processor symbols/macros ('#define')                            */
/*****************************************************************************/
/*****************************************************************************/
/* Global variable definitions (declared in header file with 'extern')       */
/*****************************************************************************/
/*****************************************************************************/
/* Local variable definitions ('static')                                     */
/*****************************************************************************/
/*****************************************************************************/
/* Local function prototypes ('static')                                      */
/*****************************************************************************/
/*****************************************************************************/
/* Function implementation - global ('extern') and local ('static')          */
/*****************************************************************************/
#define FEE_START_SEC_CODE_ASIL_B
#include "Fee_MemMap.h"

/**
 ******************************************************************************
 ** \fn Fee_ReadLib
 **
 ** Library function to read several or some bytes out of a block.
 **
 ** \param BlockNumber [in] - Number of block which shall be read.
 ** \param BlockOffset [in] - Offset in a block from where the data shall be read.
 ** \param DataBufferPtr [out] - Pointer to buffer where the data shall be read
 ** to.
 ** \param Length [in] - Number of bytes to be read.
 **
*****************************************************************************/
FUNC(Std_ReturnType, FEE_CODE) Fee_ReadLib(
  VAR(uint16, AUTOMATIC) BlockNumber,
  VAR(uint16, AUTOMATIC) BlockOffset,
  P2VAR(uint8, AUTOMATIC, FEE_APPL_DATA) DataBufferPtr,
  VAR(uint16, AUTOMATIC) Length,
  VAR(Fee_BlockAttributeType, AUTOMATIC) BlkAttri)
{
    /* job information of operation */
    Fee_Job.ConfigSetNumber               = BlkAttri.FeeConfigSetNumber;
    Fee_Job.BlockIndex                    = BlkAttri.FeeBlockIndex;
    Fee_Job.BlockNumber                   = BlockNumber;
    Fee_Job.BlockOffset                   = BlockOffset;
    Fee_Job.DataBufferPtr.ReadBufferPtr   = DataBufferPtr;
    Fee_Job.Length                        = Length;
    Fee_JobResult                         = MEMIF_JOB_PENDING;

    if( Fee_ModuleState == FEE_STAT_NOP )
    {
        if( MEMIF_IDLE == Fee_FlsGetStatus() )
        {
            FEE_STATE_SET(FEE_STAT_READ)                          /* change state */
            Fee_SetCurrentConfigNo(Fee_Job.ConfigSetNumber);      /* set global variable set */
            Fee_PeriInfo.Fee_MainState = FEE_MAIN_STATE_READING;  /* set main state */
            Fee_Counter = Fee_GetTimeoutCount(FEE_ENUMTYPE_READ); /* set counter */
        }
        else
        {
            FEE_STATE_SET(FEE_STAT_READ_WAIT)                        /* change state */
            Fee_Counter = Fee_GetTimeoutCount(FEE_ENUMTYPE_CANCEL);  /* set counter */
        }
    }
    else
    {
        FEE_STATE_SET(FEE_STAT_READ_WAIT_WRITE)                   /* change state */
    }

    return E_OK;
}

#define FEE_STOP_SEC_CODE_ASIL_B
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include "Fee_MemMap.h"

