/** \brief AUTOSAR Fee Flash EEPROM Emulation
 **
 ** This file contains the implementation of the AUTOSAR module Fee.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-FEE42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
*/

/*****************************************************************************/
/* Include files                                                             */
/*****************************************************************************/
#include "Fee_Internal.h"

/*****************************************************************************/
/* Local pre-processor symbols/macros ('#define')                            */
/*****************************************************************************/
/*****************************************************************************/
/* Global variable definitions (declared in header file with 'extern')       */
/*****************************************************************************/
/*****************************************************************************/
/* Local variable definitions ('static')                                     */
/*****************************************************************************/
/*****************************************************************************/
/* Local function prototypes ('static')                                      */
/*****************************************************************************/
/*****************************************************************************/
/* Function implementation - global ('extern') and local ('static')          */
/*****************************************************************************/
#define FEE_START_SEC_CODE_ASIL_B
#include "Fee_MemMap.h"

/**
 ******************************************************************************
 ** \fn Fee_InitLib
 **
 ** Library function to initialize the FEE.
 **
*****************************************************************************/
FUNC(void, FEE_CODE) Fee_InitLib(void)
{
    /* initialize variable for FEE */
    VAR(uint8, AUTOMATIC)  cnt;


    Fee_Job.ConfigSetNumber                = (uint8)1;
    Fee_Job.BlockIndex                     = (uint16)FEE_NULL;
    Fee_Job.BlockNumber                    = (uint16)FEE_NULL;
    Fee_Job.BlockOffset                    = (uint16)FEE_NULL;
    Fee_Job.DataBufferPtr.ReadBufferPtr    = (uint8*)NULL_PTR;
    Fee_Job.Length                         = (uint16)FEE_NULL;

    Fee_JobResult = MEMIF_JOB_PENDING;
    Fee_Counter = (uint32)FEE_INITIAL_COUNTER_NUM;
    Fee_BlockIndexAlreadyUpdated = FEE_BLOCK_INDEX_UPDATED_NO;

    Fee_InitBlkCfgOnFlash();
    
    Fee_SetCurrentConfigNo((uint8)1);
    if(STD_OFF == Fee_GetDefinedThresholdPageSize())
    {
        /* initialize variable Fee_ImmDataReserveSize */
        for( cnt = (uint8)FEE_NULL; cnt < Fee_GetCfgNum(); cnt++ )
        {
            Fee_ImmDataReserveSize[cnt] = (uint16)FEE_NULL;
        }
    }

    Fee_Reset(FEE_RESET_INIT);       /* reset FEE */

    FEE_STATE_SET(FEE_STAT_INIT)

    Fee_PeriInfo.Fee_MainState  = FEE_MAIN_STATE_INITIALIZING | FEE_MAIN_STATE_RECOVERING;   /* set main state */
    Fee_Counter = Fee_GetTimeoutCount(FEE_ENUMTYPE_INIT);
}

#define FEE_STOP_SEC_CODE_ASIL_B
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include "Fee_MemMap.h"

