/** \brief AUTOSAR Fls Flash Driver
 **
 ** This file contains the implementation of Fls sub module function
 ** Fls_GetStatusSub.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */

/*========*/
/* Header */
/*========*/
#include <Fls_LibInterface.h>   /* Library interface header file */
#include <Fls_InternalLib.h>    /* Module internal API */     


/*==================*/
/* function         */
/*==================*/

#define FLS_START_SEC_CODE
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/** \brief Fls_GetStatusSub
**
** Get status of HAL.
**
** \return     status of HAL
** \retval     FLS_STATUS_IDLE        idle
** \retval     FLS_STATUS_WAIT_IDLE   waiting for idle
** \retval     FLS_STATUS_BUSY        busy
**
*/
FUNC(FLS_UCHAR, FLS_CODE) Fls_GetStatusSub
(
 void
)
{
    FLS_UCHAR retval;                   /* return value */
    
    switch(Fls_StateSub)
    {
    case FLS_HAL_WRITE:
    case FLS_HAL_WRITE_WAIT:
    case FLS_HAL_ERASE:
    case FLS_HAL_ERASE_WAIT:
        retval = FLS_STATUS_BUSY;
        break;
    case FLS_HAL_NOP:
        
        retval = Fls_PollingFlash();
        
        switch(retval)
        {
        case FLS_HAL_NOP:
            /* idle */
        case FLS_HAL_MAX:
            /* timeout */
            Fls_WritePrivilegedRegisters( FLS_WRITE_REG_PATN_DISABLE_INTERRUPT_WRITE ); /* disable interruption */
            Fls_WritePrivilegedRegisters( FLS_WRITE_REG_PATN_DISABLE_WRITE ); /* disable writing to flash memory */
            retval = FLS_STATUS_IDLE;
            Fls_WritePrivilegedRegisters( FLS_WRITE_REG_PATN_REFRESH_REGISTERS ); /* refresh registers */
            break;
        case FLS_FMC_ACT:
            /* waiting for idle */
            retval = FLS_STATUS_WAIT_IDLE;
            break;
        default:
            break;
        }
        break;
        
    default:
        /* Fls_StateSub is corruption */
        retval = FLS_STATUS_IDLE;
        break;
    }
    
    return retval;
}
#define FLS_STOP_SEC_CODE
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/*==================[end of file]===========================================*/
