/** \brief AUTOSAR Fls Flash Driver
 **
 ** This file contains the implementation of Fls sub module function
 ** Fls_ResetSub.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */
/*========*/
/* Header */
/*========*/
#include <Fls_LibInterface.h>   /* Library interface header file */
#include <Fls_InternalLib.h>    /* Module internal API */     


/*==================*/
/* functions        */
/*==================*/

#define FLS_START_SEC_CODE
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/** \brief Fls_ResetSub
**
** Issue a reset command to the flash memory.
**
** \return     none
**
*/
FUNC(void, FLS_CODE) Fls_ResetSub
(
 void
)
{
    if( Fls_IpcLocked == FLS_TRUE )
    {
        /* Initialize internal variable. */
        Fls_DataSize    = (FLS_ULONG)FLS_NULL;
        Fls_ParamLength = (FLS_ULONG)FLS_NULL;
        Fls_ParamAddr   = (FLS_UCHAR *)FLS_NULL;

        /* Initialize internal variable. */
        Fls_NowAddr = (volatile FLS_ULONG *)FLS_NULL;
        Fls_NowData = (FLS_ULONG *)FLS_NULL;

        if( Fls_UseInterrupts == STD_ON )
        {
            if( Fls_StateSub == FLS_HAL_WRITE )
            {
                Fls_WritePrivilegedRegisters( FLS_WRITE_REG_PATN_DISABLE_INTERRUPT_WRITE ); /* disable interruption */
            }
            else
            {
                if( Fls_StateSub == FLS_HAL_ERASE )
                {
                    /* clear interrupt mask of FM_CTL_ECT */
                   (void)Fls_InvokeFMAPI( FLS_FMAPI_CONFIGURE_FM_INTERRUPT_MCLEAR, (FLS_ULONG)FLS_NULL, (FLS_ULONG)FLS_NULL );
                }
            }
        }

        FLS_STATESUB_SET(FLS_HAL_NOP)                                   /* set state */
        Fls_JobresultSub    = FLS_JOB_OK;

        Fls_WritePrivilegedRegisters( FLS_WRITE_REG_PATN_INVALIDATE_CACHE ); /* invalidate cache and buffer */
        Fls_WritePrivilegedRegisters( FLS_WRITE_REG_PATN_DISABLE_WRITE ); /* disable writing to flash memory */
    }

    return;
}
#define FLS_STOP_SEC_CODE
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/*==================[end of file]===========================================*/
