/** \brief AUTOSAR Fls Flash Driver
 **
 ** This file contains the implementation of the AUTOSAR module Fls
 ** function Fls_Cancel.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */

/*==================[inclusions]============================================*/

#include <Fls_LibInterface.h>   /* Library interface header file */
#include <Fls_InternalLib.h>    /* Module internal API */

/*==================[macros]================================================*/

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

/*==================[internal function declarations]========================*/

/*==================[external constants]====================================*/

/*==================[internal constants]====================================*/

/*==================[external data]=========================================*/

/*==================[internal data]=========================================*/

/*==================[external function definitions]=========================*/

#define FLS_START_SEC_CODE
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/** \brief Fls_CancelLib
 **
 ** Cancels an ongoing flash job immediately(read/write/erase/compare/blank check).
 ** Reset internal job processing variables and set driver state to IDLE.
 ** If configured, this function call the error notification function.
 **
 ** \return     none
 */ 
FUNC(void, FLS_CODE) Fls_CancelLib(void)
{
    P2CONST(Fls_ConfigType, AUTOMATIC, FLS_APPL_CONST) ConfigPtr;   /* Configuration address */
    uint8    Notify;       /* Fls_JobRequest.CurrentJob check flag */
    
    /* initialize internal value */
    ConfigPtr = Fls_ConfigPtr;
    Notify = FLS_FALSE;

    /* Fls356: check that driver is initialized -> FLS_E_UNINIT */
    if( Fls_DriverState == MEMIF_UNINIT )
    {
        /* report DET error */
        (void)Fls_ReportError( FLS_MODULE_ID,
                               FLS_INSTANCE_ID,
                               FLS_ID_CANCEL,
                               FLS_E_UNINIT );
    }
    else
    {
        /* enter exclusive area */
        Fls_EnterCritiSec();

        if( Fls_JobRequest.CurrentJob >= FLS_SUSPEND_RESUME )
        {
            /* exit exclusive area */
            Fls_ExitCritiSec();

            /* report DET error */
            (void)Fls_ReportError( FLS_MODULE_ID,
                                   FLS_INSTANCE_ID,
                                   FLS_ID_CANCEL,
                                   FLS_E_BUSY );
        }
        else
        {
            /* Fls229: cancel an ongoing flash read, write, erase or compare job */

            /* Fls033: set job result to MEMIF_JOB_CANCELED if it is MEMIF_JOB_PENDING */
            if( Fls_JobResult == MEMIF_JOB_PENDING )
            {
                Fls_JobResult = MEMIF_JOB_CANCELED;
            }

            /* Fls_JobRequest.CurrentJob is reset later, because it needs to be evaluated below */
            /* Fls335: reset internal job processing variables */
            /* Fls336: set driver state to MEMIF_IDLE */
            Fls_DriverState = MEMIF_IDLE;
            Fls_JobRequest.LogFlashAddress = 0UL;
            Fls_JobRequest.RamAddress      = 0UL;
            Fls_JobRequest.Length          = 0UL;
            Fls_JobRequest.CurrentLength   = 0UL;

            Fls_JobRequest.ResetLength     = 0UL;

            /* clear Fls_MainFunctionTime */
            Fls_JobRequest.Fls_MainFunctionTime = FLS_MAX_TIME_INIT;

            /* when current job is nothing */
            if( Fls_JobRequest.CurrentJob == FLS_IDLE )
            {
                /* do nothing */
            }
            /* when current job is runnung */
            else
            {
                /* Fls_JobRequest.CurrentJob is reset */
                Fls_JobRequest.CurrentJob = FLS_IDLE;
                Notify = FLS_TRUE;
            }

            /* Fls335: call cancel routine of flash driver engine */
            Fls_CancelSub();

            /* call Fls_GetStatusSub in order to disable writing to flash memory */
            (void)Fls_GetStatusSub();

            /* exit exclusive area */
            Fls_ExitCritiSec();

            /* Fls147: if configured call the error notification function */
            if( ( ConfigPtr->JobErrorNotifFctPtr != NULL_PTR ) &&
                  ( Notify == FLS_TRUE ) )
            {
                ConfigPtr->JobErrorNotifFctPtr();
            }
        }
    }

    return;
}

#define FLS_STOP_SEC_CODE
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/*==================[internal function definitions]=========================*/

/*==================[end of file]===========================================*/
