/** \brief AUTOSAR Fls Flash Driver
 **
 ** This file contains the implementation of the AUTOSAR module Fls
 ** function Fls_Resume.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */

/*==================[inclusions]============================================*/

#include <Fls_LibInterface.h>   /* Library interface header file */
#include <Fls_InternalLib.h>    /* Module internal API */

/*==================[macros]================================================*/

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

/*==================[internal function declarations]========================*/

/*==================[external constants]====================================*/

/*==================[internal constants]====================================*/

/*==================[external data]=========================================*/

/*==================[internal data]=========================================*/

/*==================[external function definitions]=========================*/

#define FLS_START_SEC_CODE
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/** \brief Fls_ResumeLib
 **
 ** This function implements resuming a suspended Fls operation.
 **
 ** \return    resume has been accepted/not been accepted
 ** \retval    E_NOT_OK         no operation was suspended or the suspended operation
 **                             cannot be resumed because there is a Fls operation
 **                             in progress already
 **            E_OK             an operation was suspended and could be resumed
 **
 */ 
FUNC(Std_ReturnType, FLS_CODE) Fls_ResumeLib(void)
{
    uint8 Ret;       /* return value */

    /* Fls356: check that driver is initialized -> FLS_E_UNINIT */
    if( Fls_DriverState == MEMIF_UNINIT )
    {
        /* report DET error */
        (void)Fls_ReportError( FLS_MODULE_ID,
                               FLS_INSTANCE_ID,
                               FLS_ID_RESUME,
                               FLS_E_UNINIT );

        /* set E_NOT_OK for return value  */
        Ret = E_NOT_OK;
    }
    else
    {
        /* enter exclusive area */
        Fls_EnterCritiSec();

        /* check if there is not Fls operation in progress already and an operation was suspended and could be resumed */
        if( ( Fls_DriverState == MEMIF_IDLE ) && ( Fls_SuspendedJobRequest.CurrentJob != FLS_IDLE ) )
        {
            Fls_DriverState = MEMIF_BUSY;
            /* Deviation from MISRA-C:2004 rule 10.1, MISRA-C:2012 Rule-10.1, Rule-10.3.
               Justification: This implemetation is because speed of addition/subtraction
               and readability would outweigh the benefit of ISO compliance. */
            /* PRQA S 4432,4521 5 */
            Fls_JobRequest.CurrentJob += FLS_SUSPEND_RESUME;

            Ret = Fls_ResumeSub();

            Fls_JobRequest.CurrentJob -= FLS_SUSPEND_RESUME;

            if( Ret == FLS_REQUEST_ACCEPT )
            {
                /* restore data for the suspended job */
                Fls_JobRequest.LogFlashAddress       = Fls_SuspendedJobRequest.LogFlashAddress;
                Fls_JobRequest.RamAddress            = Fls_SuspendedJobRequest.RamAddress;
                Fls_JobRequest.Length                = Fls_SuspendedJobRequest.Length;
                Fls_JobRequest.CurrentLength         = Fls_SuspendedJobRequest.CurrentLength;
                Fls_JobRequest.CurrentJob            = Fls_SuspendedJobRequest.CurrentJob;
                Fls_JobRequest.ResetLength           = Fls_SuspendedJobRequest.ResetLength;
                Fls_JobRequest.Fls_MainFunctionTime  = Fls_SuspendedJobRequest.Fls_MainFunctionTime;
                Fls_JobRequest.ReadWithoutBlankCheck = Fls_SuspendedJobRequest.ReadWithoutBlankCheck;
                Fls_JobRequest.Fls_RetryTime         = 0U;

                Fls_WriteGlobalJob.FlashAddress      = Fls_WriteGlobalSuspendedJob.FlashAddress;
                Fls_WriteGlobalJob.LogicalAddress    = Fls_WriteGlobalSuspendedJob.LogicalAddress;
                Fls_WriteGlobalJob.Length            = Fls_WriteGlobalSuspendedJob.Length;
                Fls_WriteGlobalJob.CheckAreaSize     = Fls_WriteGlobalSuspendedJob.CheckAreaSize;

                /* suspended job is nothing */
                Fls_SuspendedJobRequest.LogFlashAddress       = 0UL;
                Fls_SuspendedJobRequest.RamAddress            = 0UL;
                Fls_SuspendedJobRequest.Length                = 0UL;
                Fls_SuspendedJobRequest.CurrentLength         = 0UL;
                Fls_SuspendedJobRequest.CurrentJob            = FLS_IDLE;
                Fls_SuspendedJobRequest.ResetLength           = 0UL;
                Fls_SuspendedJobRequest.Fls_MainFunctionTime  = FLS_MAX_TIME_INIT;
                Fls_SuspendedJobRequest.ReadWithoutBlankCheck = FLS_FALSE;

                /* resume a suspended job */
                Fls_JobResult = MEMIF_JOB_PENDING;

                /* set E_OK for return value  */
                Ret = E_OK;
            }
            else
            {
                /* continue suspending a current job */
                Fls_DriverState = MEMIF_IDLE;

                /* set E_NOT_OK for return value */
                Ret = E_NOT_OK;
            }
        }
        else
        {
            /* set E_NOT_OK for return value */
            Ret = E_NOT_OK;
        }

        /* exit exclusive area */
        Fls_ExitCritiSec();
    }

    return Ret;
}

#define FLS_STOP_SEC_CODE
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1.
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Fls_MemMap.h>

/*==================[internal function definitions]=========================*/

/*==================[end of file]===========================================*/
