/** \brief AUTOSAR Dio DIO Driver
 **
 ** This file contains implementations of internal function
 ** for the AUTOSAR Dio driver.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */
/*==================[inclusions]=============================================*/
#include <Dio_Internal.h>     /* internal header for module Dio */
#include <Dio_HwAccess.h>     /* Interface header for Hwaccess */

/*==================[macros]=================================================*/
#define DIO_CHANNEL_WIDTH_SHIFT_VALUE 3U
#define DIO_CHANNEL_WIDTH_ADD_VALUE   0x07U

/*==================[type definitions]=======================================*/

/*==================[external function declarations]=========================*/

/*==================[internal function declarations]=========================*/
#define DIO_START_SEC_CODE_ASIL_B
#include <Dio_MemMap.h>

/** \brief Dio_GetPortNumber
 **
 ** Get the port number.
 ** This function get the port number of the target from the channel ID.
 **
 ** \param[in]  ChannelId  The ID of the DIO channel.
 **
 ** \retval     ID of the port including the specified channel.
 ** */
static FUNC(uint8, DIO_CODE) Dio_GetPortNumber(
    Dio_ChannelType ChannelId
    );

/** \brief Dio_GetPinNumber
 **
 ** Get the pin number.
 ** This function get the pin number of hardware.
 **
 ** \param[in]  ChannelId  The ID of the DIO channel.
 **
 ** \retval     Pin number of hardware for the specified channel.
 ** */
static FUNC(uint8, DIO_CODE) Dio_GetPinNumber(
    Dio_ChannelType ChannelId
    );

#define DIO_STOP_SEC_CODE_ASIL_B
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1
   Justification: In AUTOSAR specification, it is a necessary process. */
/* PRQA S 5087 1 */
#include <Dio_MemMap.h>
/*==================[external constants]=====================================*/

/*==================[internal constants]=====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

#define DIO_START_SEC_CODE_ASIL_B
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1
   Justification: In AUTOSAR specification, it is a necessary process. */
/* PRQA S 5087 1 */
#include <Dio_MemMap.h>

/** \brief Dio_ReadChannel_Internal
 **
 ** This function returns the value of the specified DIO channel.
 **
 ** \param[in]  ChannelId  The ID of the DIO channel.
 ** \param[in]  Dio_DriverConfigPtr  This structure contains all post-build
 **             configurable parameters of the DIO driver.
 **
 ** \retval     Channel level.
 **             STD_HIGH:The physical level of the corresponding Pin is high.
 **             STD_LOW:The physical level of the corresponding Pin is low.
 ** */
FUNC(Dio_LevelType, DIO_CODE) Dio_ReadChannel_Internal(
    Dio_ChannelType ChannelId,
    P2CONST(Dio_ConfigType, AUTOMATIC, DIO_CONST) Dio_DriverConfigPtr
)
{
    Dio_LevelType Result;             /* temporary variable for return value */
    uint8 portId;                     /* temporary variable for port number */
    uint32 bitNumber = 1u;            /* temporary variable for mask bit */
    Dio_PortLevelType ReadData;       /* temporary variable for read data */
    
    /* get the ID of the port  */
    portId = Dio_GetPortNumber(ChannelId);
    /* read the specified port */
    ReadData = Dio_HwRead(Dio_DriverConfigPtr->portConfigPtr[portId].HwPortNumber,
    &Dio_DriverConfigPtr->IOPortRegisterInfo);
    
    /* get the pin number of hardware */
    bitNumber <<= Dio_GetPinNumber(ChannelId);
    
    /* check the level of the specified channel */
    if((bitNumber & (uint32)ReadData) != 0u)
    {
        Result = (Dio_LevelType)STD_HIGH;
    }
    else {
        Result = (Dio_LevelType)STD_LOW;
    }
    return Result;
}

/** \brief Dio_WriteChannel_Internal
 **
 ** This function write the value of the specified DIO channel.
 **
 ** \param[in]  ChannelId  The ID of the DIO channel.
 ** \param[in]  Level      The value to write.
 ** \param[in]  Dio_DriverConfigPtr  This structure contains all post-build
 **             configurable parameters of the DIO driver.
 **
 ** \retval     none
 ** */
FUNC(void, DIO_CODE) Dio_WriteChannel_Internal(
    Dio_ChannelType ChannelId, Dio_LevelType Level,
    P2CONST(Dio_ConfigType, AUTOMATIC, DIO_CONST) Dio_DriverConfigPtr
)
{
    uint8 portId;                  /* temporary variable for port number */
    
    /* get the ID of the port  */
    portId = Dio_GetPortNumber(ChannelId);
    
    /* write the specified channel */
    Dio_HwWriteChannel(Dio_GetPinNumber(ChannelId),
    Dio_DriverConfigPtr->portConfigPtr[portId].HwPortNumber, Level,
    &Dio_DriverConfigPtr->IOPortRegisterInfo);
    
    return;
}

/** \brief Dio_ReadPort_Internal
 **
 ** This function returns the value of the specified DIO port.
 **
 ** \param[in]  PortId  The ID of the DIO port.
 ** \param[in]  Dio_DriverConfigPtr  This structure contains all post-build
 **             configurable parameters of the DIO driver.
 **
 ** \retval     Level of all channels of that port.
 ** */
FUNC(Dio_PortLevelType, DIO_CODE) Dio_ReadPort_Internal(
    Dio_PortType PortId, 
    P2CONST(Dio_ConfigType, AUTOMATIC, DIO_CONST) Dio_DriverConfigPtr
)
{
    Dio_PortLevelType Result;    /* temporary variable for return value */
    
    /* read the specified port */
    Result = Dio_HwRead(Dio_DriverConfigPtr->portConfigPtr[PortId].HwPortNumber,
    &Dio_DriverConfigPtr->IOPortRegisterInfo);
    
    return Result;
}

/** \brief Dio_WritePort_Internal
 **
 ** This function write the value of the specified DIO port.
 **
 ** \param[in]  PortId  The ID of the DIO port.
 ** \param[in]  Level   The value to write.
 ** \param[in]  Dio_DriverConfigPtr  This structure contains all post-build
 **             configurable parameters of the DIO driver.
 **
 ** \retval     none
 ** */
FUNC(void, DIO_CODE) Dio_WritePort_Internal(
    Dio_PortType PortId, Dio_PortLevelType Level,
    P2CONST(Dio_ConfigType, AUTOMATIC, DIO_CONST) Dio_DriverConfigPtr
)
{
    /* write the specified port */
    Dio_HwWritePort(Dio_DriverConfigPtr->portConfigPtr[PortId].HwPortNumber,Level,
    &Dio_DriverConfigPtr->IOPortRegisterInfo);
    
    return;
}

/** \brief Dio_MaskedWritePort_Internal
 **
 ** This function write the masked value of the specified DIO port.
 **
 ** \param[in]  PortId  The ID of the DIO port.
 ** \param[in]  Level   The value to write.
 ** \param[in]  Mask    The value of mask.
 ** \param[in]  Dio_DriverConfigPtr  This structure contains all post-build
 **             configurable parameters of the DIO driver.
 **
 ** \retval     none
 ** */
FUNC(void, DIO_CODE) Dio_MaskedWritePort_Internal(
    Dio_PortType PortId, Dio_PortLevelType Level, Dio_PortLevelType Mask,
    P2CONST(Dio_ConfigType, AUTOMATIC, DIO_CONST) Dio_DriverConfigPtr
)
{
    /* write the specified port */
    Dio_HwMaskedWritePort(Dio_DriverConfigPtr->portConfigPtr[PortId].HwPortNumber,
    Mask, Level, &Dio_DriverConfigPtr->IOPortRegisterInfo);
    
    return;
}

/** \brief Dio_ReadChannelGroup_Internal
 **
 ** This function returns the value of the specified DIO channel group.
 **
 ** \param[in]  ChannelGroupIdPtr  Pointer to Channel Group.
 ** \param[in]  Dio_DriverConfigPtr  This structure contains all post-build
 **             configurable parameters of the DIO driver.
 **
 ** \retval     Level of channel groups.
 ** */
FUNC(Dio_PortLevelType, DIO_CODE) Dio_ReadChannelGroup_Internal(
    P2CONST(Dio_ChannelGroupType, AUTOMATIC, DIO_CONST) ChannelGroupIdPtr,
    P2CONST(Dio_ConfigType, AUTOMATIC, DIO_CONST) Dio_DriverConfigPtr
)
{
    Dio_PortLevelType Result;    /* temporary variable for return value */
    
    /* read the specified port */
    Result = Dio_HwRead(Dio_DriverConfigPtr->portConfigPtr[(uint8)ChannelGroupIdPtr->port].HwPortNumber,
    &Dio_DriverConfigPtr->IOPortRegisterInfo);
    /* create the level of the specified channel group */
    Result = (Result & ChannelGroupIdPtr->mask) >> ChannelGroupIdPtr->offset;
    
    return Result;
}

/** \brief Dio_WriteChannelGroup_Internal
 **
 ** This function write the value of the specified DIO channel group.
 **
 ** \param[in]  ChannelGroupIdPtr  Pointer to Channel Group.
 ** \param[in]  Level   The value to write.
 ** \param[in]  Dio_DriverConfigPtr  This structure contains all post-build
 **             configurable parameters of the DIO driver.
 **
 ** \retval     none
 ** */
FUNC(void, DIO_CODE) Dio_WriteChannelGroup_Internal(
    P2CONST(Dio_ChannelGroupType, AUTOMATIC, DIO_CONST) ChannelGroupIdPtr,
    Dio_PortLevelType Level,
    P2CONST(Dio_ConfigType, AUTOMATIC, DIO_CONST) Dio_DriverConfigPtr
)
{
    /* create the level of port */
    Level = Level << ChannelGroupIdPtr->offset;
    /* write the specified channel group */
    Dio_HwMaskedWritePort(Dio_DriverConfigPtr->portConfigPtr[(uint8)ChannelGroupIdPtr->port].HwPortNumber,
    ChannelGroupIdPtr->mask, Level, &Dio_DriverConfigPtr->IOPortRegisterInfo);
    
    return;
}

/** \brief Dio_FlipChannel_Internal
 **
 ** This function flip (change from 1 to 0 or from 0 to 1) the level 
 ** of a channel and return the level of the channel after flip.
 **
 ** \param[in]  ChannelId  The ID of the DIO channel.
 ** \param[in]  Dio_DriverConfigPtr  This structure contains all post-build
 **             configurable parameters of the DIO driver.
 **
 ** \retval     Channel level.
 **             STD_HIGH:The physical level of the corresponding Pin is high.
 **             STD_LOW:The physical level of the corresponding Pin is low.
 ** */
FUNC(Dio_LevelType, DIO_CODE) Dio_FlipChannel_Internal(
    Dio_ChannelType ChannelId,
    P2CONST(Dio_ConfigType, AUTOMATIC, DIO_CONST) Dio_DriverConfigPtr
)
{
    Dio_LevelType Result;           /* temporary variable for return value */
    uint8 portId;                   /* temporary variable for port number */
    uint8 pinNumberForMask;         /* Specifies the target pin in the port */
    Dio_PortLevelType ReadData;     /* temporary variable for read data */
    
    /* get the ID of the port  */
    portId = Dio_GetPortNumber(ChannelId);
    
    /* get the number of specifies the target pin */
    pinNumberForMask = Dio_GetPinNumber(ChannelId);
    
    /* flip the specified channel */
    Dio_HwFlip(Dio_DriverConfigPtr->portConfigPtr[portId].HwPortNumber,
    pinNumberForMask, &Dio_DriverConfigPtr->IOPortRegisterInfo);
    
    /* read the specified port */
    ReadData = Dio_HwRead(Dio_DriverConfigPtr->portConfigPtr[portId].HwPortNumber,
    &Dio_DriverConfigPtr->IOPortRegisterInfo);
    
    if ((ReadData & ((uint32)1u << pinNumberForMask)) != (uint32)0u)
    {
        Result = (Dio_LevelType)STD_HIGH;
    }
    else
    {
        Result = (Dio_LevelType)STD_LOW;
    }
    
    return Result;
}

/** \brief Dio_isValidChannel
 **
 ** This function checks the validity of a specified channel.
 **
 ** \param[in]  Dio_DriverConfigPtr  This structure contains all post-build
 **             configurable parameters of the DIO driver.
 ** \param[in]  ChannelId  The ID of the DIO channel.
 **
 ** \retval     Validity of a ChannelId.
 **             TRUE  : valid ChannelId.
 **             FALSE : invalid ChannelId.
 ** */
FUNC(boolean, DIO_CODE) Dio_isValidChannel(
    P2CONST(Dio_ConfigType, AUTOMATIC, DIO_CONST) Dio_DriverConfigPtr,
    Dio_ChannelType ChannelId
)
{
    boolean Result = FALSE;     /* temporary variable for return value */
    uint8 hwPin;                /* temporary variable for pin number */
    uint8 portId;               /* temporary variable for port number */
    uint32 bitNumber = 1u;      /* temporary variable for mask bit */
    
    /* check the valid port */
    portId = Dio_GetPortNumber(ChannelId);
    if(portId < Dio_DriverConfigPtr->numberOfPorts)
    {
        /* get the pin number of hardware */
        hwPin = Dio_GetPinNumber(ChannelId);
        bitNumber <<= hwPin;
        /* check the valid pin */
        if((bitNumber & (uint32)Dio_DriverConfigPtr->portConfigPtr[portId].portMask) != 0u)
        {
            Result = TRUE;
        }
    }
    return Result;
}

/** \brief Dio_isValidPort
 **
 ** This function checks the validity of a specified port.
 **
 ** \param[in]  Dio_DriverConfigPtr  This structure contains all post-build
 **             configurable parameters of the DIO driver.
 ** \param[in]  PortId  The ID of the DIO port.
 **
 ** \retval     Validity of a PortId.
 **             TRUE  : valid PortId.
 **             FALSE : invalid PortId.
 ** */
FUNC(boolean, DIO_CODE) Dio_isValidPort(
    P2CONST(Dio_ConfigType, AUTOMATIC, DIO_CONST) Dio_DriverConfigPtr,
    Dio_PortType PortId
)
{
    boolean Result = FALSE;     /* temporary variable for return value */
    
    /* check the valid port */
    if(PortId < Dio_DriverConfigPtr->numberOfPorts)
    {
        if((uint32)Dio_DriverConfigPtr->portConfigPtr[PortId].portMask != 0u)
        {
            Result = TRUE;
        }
    }
    return Result;
}

/** \brief Dio_isValidChannelGroup
 **
 ** This function checks the validity of a specified channel group.
 **
 ** \param[in]  Dio_DriverConfigPtr  This structure contains all post-build
 **             configurable parameters of the DIO driver.
 ** \param[in]  ChannelGroupIdPtr  Pointer to Channel Group.
 **
 ** \retval     Validity of a channel group.
 **             TRUE  : valid channel group.
 **             FALSE : invalid channel group.
 ** */
FUNC(boolean, DIO_CODE) Dio_isValidChannelGroup(
    P2CONST(Dio_ConfigType, AUTOMATIC, DIO_CONST) Dio_DriverConfigPtr,
    P2CONST(Dio_ChannelGroupType, AUTOMATIC, DIO_CONST) ChannelGroupIdPtr
)
{
    boolean Result = FALSE;     /* temporary variable for return value */
    
    /* check the valid chennel group */
    if ((ChannelGroupIdPtr != NULL_PTR) &&
        (ChannelGroupIdPtr->port < Dio_DriverConfigPtr->numberOfPorts))
    {
        Result = TRUE;
    }
    return Result;
}

#define DIO_STOP_SEC_CODE_ASIL_B
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1
   Justification: In AUTOSAR specification, it is a necessary process. */
/* PRQA S 5087 1 */
#include <Dio_MemMap.h>

/*==================[internal function definitions]==========================*/

#define DIO_START_SEC_CODE_ASIL_B
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1
   Justification: In AUTOSAR specification, it is a necessary process. */
/* PRQA S 5087 1 */
#include <Dio_MemMap.h>

/** \brief Dio_GetPortNumber
 **
 ** This function get the port number of the target from the channel ID.
 **
 ** \param[in]  ChannelId  The ID of the DIO channel.
 **
 ** \retval     ID of the port including the specified channel.
 ** */
static FUNC(uint8, DIO_CODE) Dio_GetPortNumber(
    Dio_ChannelType ChannelId
)
{
  uint8 Result;             /* temporary variable for return value */
  
  /* get the port ID */
  Result = (uint8)(ChannelId >> DIO_CHANNEL_WIDTH_SHIFT_VALUE);
  
  return Result;
}

/** \brief Dio_GetPinNumber
 **
 ** This function get the pin number of hardware.
 **
 ** \param[in]  ChannelId  The ID of the DIO channel.
 **
 ** \retval     Pin number of hardware for the specified channel.
 ** */
static FUNC(uint8, DIO_CODE) Dio_GetPinNumber(
    Dio_ChannelType ChannelId
)
{
  uint8 Result;             /* temporary variable for return value */
  
  /* get the pin number */
  Result = (uint8)((ChannelId) & (Dio_ChannelType)DIO_CHANNEL_WIDTH_ADD_VALUE);
  
  return Result;
}

#define DIO_STOP_SEC_CODE_ASIL_B
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1
   Justification: In AUTOSAR specification, it is a necessary process. */
/* PRQA S 5087 1 */
#include <Dio_MemMap.h>

/*==================[end of file]============================================*/
