/** \brief Pwm_Det.h
 **
 ** This file contains development error processing macros
 ** used by the library.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */

#ifndef PWM_DET_H_INCLUDED
#define PWM_DET_H_INCLUDED

/*==================[inclusions]=============================================*/
#include <Pwm_Cfg.h>  /* Include generated configuration with all symbolic names */

#if !(defined PWM_DEV_ERROR_DETECT)
#error "PWM_DEV_ERROR_DETECT not set"
#endif /* if !(defined PWM_DEV_ERROR_DETECT) */

#if (PWM_DEV_ERROR_DETECT==STD_ON)
#include <Det.h>
#endif /* if (PWM_DEV_ERROR_DETECT==STD_ON) */

/*==================[macros]=================================================*/
#if (defined PWM_INSTANCE_ID) /* To prevent double declaration */
#error PWM_INSTANCE_ID already defined
#endif /* if (defined PWM_INSTANCE_ID) */

/** Identifier of PWM module instance. */
#define PWM_INSTANCE_ID      ((uint8) 0u)

/*==================[type definitions]=======================================*/

/*==================[external function declarations]==========================*/

#define PWM_START_SEC_CODE_ASIL_B
#include <Pwm_MemMap.h>

/** \brief Pwm_ReportError
 **
 ** Reports an error to the error handler and optionally to the DET.
 **
 ** \param [in] ErrorId   Error identifier.
 ** \param [in] ApiId     API identifier.
 **
 */
extern FUNC(void, PWM_CODE) Pwm_ReportError
(
  VAR(uint8, AUTOMATIC) ErrorId,
  VAR(uint8, AUTOMATIC) ApiId
);

#define PWM_STOP_SEC_CODE_ASIL_B
#include <Pwm_MemMap.h>

/*==================[internal function declarations]==========================*/

/*==================[external constants]=====================================*/

/*==================[internal constants]====================================*/

/*==================[external data]==========================================*/

/*==================[internal data]==========================================*/

/*==================[external function definitions]==========================*/

/*==================[internal function definitions]==========================*/

/*==================[end of file]===========================================*/

#endif /*!defined(PWM_DET_H_INCLUDED)*/
