
#ifndef WDG_66_IA_CONTROLLER_H
#define WDG_66_IA_CONTROLLER_H 1

/** \brief AUTOSAR Wdg Driver
 **
 ** This file contains functions to control the watchdog driver.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */

/*==================[inclusions]=============================================*/

#include <Std_Types.h>          /* AUTOSAR standard types */
#include <Wdg_66_IA_Types.h>

/*==================[type definitions]=======================================*/
/*==================[external function declarations]=========================*/
/*==================[internal function declarations]=========================*/

#define WDG_66_IA_START_SEC_CODE
#include <Wdg_66_IA_MemMap.h>

/** \brief Wdg_66_IA_Internal_Init
 **
 ** This function initializes watchdog driver according to configuration.
 **
 ** \param [in] ConfigPtr  Pointer to configuration which be used to initialize
 **                        watchdog driver.
 **
 ** \return E_OK:     Initialization has been successfully completed.
 **         E_NOT_OK: Initialization has been failed.
 */
extern FUNC( Std_ReturnType, WDG_CODE )
Wdg_66_IA_Internal_Init(
  P2CONST( Wdg_66_IA_ConfigType, AUTOMATIC, WDG_APPL_CONST ) ConfigPtr
);

/** \brief Wdg_66_IA_Internal_SetMode
 **
 ** This function switches watchdog module into the mode 'Mode'.
 **
 ** \param [in] Mode        One of the three different modes.
 ** \para  [in] ConfigPtr   A pointer to configuration setting.
 **
 ** \return E_OK: Switching has been finished without errors.
 **         E_NOT_OK: Switching has been failed (Not supported).
 */
extern FUNC( Std_ReturnType, WDG_CODE )
Wdg_66_IA_Internal_SetMode(
  WdgIf_ModeType Mode,
  P2CONST( Wdg_66_IA_ConfigType, AUTOMATIC, WDG_APPL_CONST ) ConfigPtr
);

/** \brief Wdg_66_IA_Internal_SetTriggerCondition
 **
 ** This function sets a timeout value for a trigger-timer counter.
 **
 ** \param [in] timeout    The timeout value (milliseconds) for setting the
 **                        trigger counter.
 ** \param [in] ConfigPtr  A pointer to configuration setting.
 */
extern FUNC( void, WDG_CODE )
Wdg_66_IA_Internal_SetTriggerCondition(
  uint16 timeout,
  P2CONST( Wdg_66_IA_ConfigType, AUTOMATIC, WDG_APPL_CONST ) ConfigPtr
);

/** \brief Wdg_66_IA_Internal_GetStatus
 **
 ** This function obtains the driver status of the module.
 **
 ** \return WDG_66_IA_UNINIT: Watchdog module is not initialized yet.
 **         WDG_66_IA_IDLE  : Watchdog module is idle.
 **         WDG_66_IA_BUSY  : Watchdog module is running.
 */
extern FUNC( Wdg_66_IA_StatusType, WDG_CODE )
Wdg_66_IA_Internal_GetStatus( void );

/** \brief Wdg_66_IA_SetupTriggerFunction
 **
 ** This function is used to copy a trigger routine into RAM area (if WdgRunArea
 ** is set to RAM) in the Wdg module.
 **
 */
extern FUNC( void, WDG_CODE )
Wdg_66_IA_SetupTriggerFunction( void );

/** \brief Wdg_66_IA_ActivateTrigger
 **
 ** This function triggers watchdog hardware.
 ** \param [in] TimerKind  One of the following watchdog timer:
 **                        0. WDG_66_IA_TIMER_MCWDT0
 **                        1. WDG_66_IA_TIMER_MCWDT1
 **                        2. WDG_66_IA_TIMER_MCWDT2
 **                        3. WDG_66_IA_TIMER_MCWDT3
 **                        4. WDG_66_IA_TIMER_WDT
 */
extern FUNC( void, WDG_CODE )
Wdg_66_IA_ActivateTrigger( Wdg_66_IA_TimerKindType TimerKind );

/** \brief Wdg_66_IA_GetPointerToSRSSRegister
 **
 ** This function is used inside the wdg module to provide service to obtain
 ** a pointer to SRSS registers.
 **
 ** \return A pointer to configuration setting.
 */
extern FUNC_P2VAR( volatile Wdg_66_IA_SrssRegType, AUTOMATIC, WDG_CODE )
Wdg_66_IA_GetPointerToSRSSRegister( void );

/** \brief Wdg_66_IA_GetPointerToConfiguration
 **
 ** This function provides a caller with the configuration which be used to 
 ** initialize watchdog driver.
 **
 ** \return a pointer to configuration which be used to initialize watchdog driver.
 */
extern FUNC_P2CONST( Wdg_66_IA_ConfigType, AUTOMATIC, WDG_CODE )
Wdg_66_IA_GetPointerToConfiguration( void );

/** \brief Wdg_66_IA_Internal_ClearWarningIrq
 **
 ** This function clears the warning interrupt flag of watchdog.
 **
 ** \param [in] TimerKind  One of the following watchdog timer:
 **                        0. WDG_66_IA_TIMER_MCWDT0
 **                        1. WDG_66_IA_TIMER_MCWDT1
 **                        2. WDG_66_IA_TIMER_MCWDT2
 **                        3. WDG_66_IA_TIMER_MCWDT3
 **                        4. WDG_66_IA_TIMER_WDT
 ** \param [in] SrssRegisterPtr  Pointer to hardware which be used to access
 **                              its registers.
 **
 */
extern FUNC( void, WDG_CODE )
Wdg_66_IA_Internal_ClearWarningIrq(
  Wdg_66_IA_TimerKindType TimerKind,
  P2VAR( volatile Wdg_66_IA_SrssRegType, AUTOMATIC, REGSPACE ) SrssRegisterPtr
);

/** \brief Wdg_66_IA_Internal_IsInterruptPending
 **
 ** This function check whether interrupt for watchdog is pending.
 **
 ** \param [in] TimerKind  One of the following watchdog timer:
 **                        0. WDG_66_IA_TIMER_MCWDT0
 **                        1. WDG_66_IA_TIMER_MCWDT1
 **                        2. WDG_66_IA_TIMER_MCWDT2
 **                        3. WDG_66_IA_TIMER_MCWDT3
 **                        4. WDG_66_IA_TIMER_WDT
 ** \param [in] SrssRegisterPtr  Pointer to hardware which be used to access
 **                              its registers.
 **
 ** \return  Return TRUE if watchdog interrupt is pending, else return FALSE.
 */
extern FUNC( boolean, WDG_CODE )
Wdg_66_IA_Internal_IsInterruptPending(
  Wdg_66_IA_TimerKindType TimerKind,
  P2CONST( volatile Wdg_66_IA_SrssRegType, AUTOMATIC, REGSPACE ) SrssRegisterPtr
);

#define WDG_66_IA_STOP_SEC_CODE
#include <Wdg_66_IA_MemMap.h>

/*==================[external constants]=====================================*/
/*==================[internal constants]=====================================*/
/*==================[external data]==========================================*/
/*==================[internal data]==========================================*/
/*==================[external function definitions]==========================*/
/*==================[internal function definitions]==========================*/

#endif /* if !defined( WDG_66_IA_CONTROLLER_H ) */
/*==================[end of file]============================================*/
