
#ifndef WDG_66_IA_HWACCESS_H
#define WDG_66_IA_HWACCESS_H 1

/** \brief AUTOSAR Wdg Driver
 **
 ** This file contains HARDWARE watchdog access interface used by the library.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */

/*==================[inclusions]=============================================*/

#include <Std_Types.h>          /* AUTOSAR standard types */

/*==================[macros]=================================================*/

/* The bit position to the register related to Watchdog Timer */
#define WDG_66_IA_REG_BIT_WDT_CTL_ENABLE             ( 0x80000000U )
#define WDG_66_IA_REG_BIT_WDT_CTL_DISABLE            ( 0x7FFFFFFFU )
#define WDG_66_IA_REG_BIT_WDT_CTL_STATUS_ENABLED     ( 0x00000001U )
#define WDG_66_IA_REG_BIT_WDT_CTL_STATUS_DISABLED    ( 0x00000000U )
#define WDG_66_IA_REG_BIT_WDT_CONFIG_LOWER_ACTION    ( 0x00000001U )
#define WDG_66_IA_REG_BIT_WDT_CONFIG_UPPER_ACTION    ( 0x00000010U )
#define WDG_66_IA_REG_BIT_WDT_CONFIG_WARN_ACTION     ( 0x00000100U )
#define WDG_66_IA_REG_BIT_WDT_CONFIG_DPSLP_PAUSE     ( 0x20000000U )
#define WDG_66_IA_REG_BIT_WDT_CONFIG_HIB_PAUSE       ( 0x40000000U )
#define WDG_66_IA_REG_BIT_WDT_CONFIG_DEBUG_RUN       ( 0x80000000U )
#define WDG_66_IA_REG_BIT_WDT_LOCK_CLR0              ( 0x00000001U )
#define WDG_66_IA_REG_BIT_WDT_LOCK_CLR1              ( 0x00000002U )
#define WDG_66_IA_REG_BIT_WDT_LOCK_SET01             ( 0x00000003U )
#define WDG_66_IA_REG_BIT_WDT_SERVICE_SERVICE        ( 0x00000001U )
#define WDG_66_IA_REG_BIT_WDT_INTR_CLR               ( 0x00000001U )
#define WDG_66_IA_REG_BIT_WDT_INTR_ENABLE            ( 0x00000001U )
#define WDG_66_IA_REG_BIT_WDT_INTR_DISABLE           ( 0x00000000U )
#define WDG_66_IA_REG_BIT_WDT_INTR_MASKED            ( 0x00000001U )

/* The bit position to the register related to Multi-Counter Watchdog Timer */
#define WDG_66_IA_REG_BIT_MCWDT_CTL_ENABLE           ( 0x80000000U )
#define WDG_66_IA_REG_BIT_MCWDT_CTL_DISABLE          ( 0x7FFFFFFFU )
#define WDG_66_IA_REG_BIT_MCWDT_CTL_STATUS_ENABLED   ( 0x00000001U )
#define WDG_66_IA_REG_BIT_MCWDT_CTL_STATUS_DISABLED  ( 0x00000000U )
#define WDG_66_IA_REG_BIT_MCWDT_CONFIG_UPPER_ACTION_FAULT  ( 0x00000010U )
#define WDG_66_IA_REG_BIT_MCWDT_CONFIG_UPPER_ACTION_FAULT_RESET  ( 0x00000020U )
#define WDG_66_IA_REG_BIT_MCWDT_CONFIG_LOWER_ACTION_FAULT  ( 0x00000001U )
#define WDG_66_IA_REG_BIT_MCWDT_CONFIG_LOWER_ACTION_FAULT_RESET  ( 0x00000002U )
#define WDG_66_IA_REG_BIT_MCWDT_CONFIG_WARN_ACTION   ( 0x00000100U )
#define WDG_66_IA_REG_BIT_MCWDT_CONFIG_DPSLP_PAUSE   ( 0x40000000U )
#define WDG_66_IA_REG_BIT_MCWDT_CONFIG_DEBUG_RUN     ( 0x80000000U )
#define WDG_66_IA_REG_BIT_MCWDT_LOCK_CLR0            ( 0x00000001U )
#define WDG_66_IA_REG_BIT_MCWDT_LOCK_CLR1            ( 0x00000002U )
#define WDG_66_IA_REG_BIT_MCWDT_LOCK_SET01           ( 0x00000003U )
#define WDG_66_IA_REG_BIT_MCWDT_SERVICE_SERVICE      ( 0x00000001U )
#define WDG_66_IA_REG_BIT_MCWDT_SERVICE_REFLECTED    ( 0x00000000U )
#define WDG_66_IA_REG_BIT_MCWDT_INTR_CLR             ( 0x00000001U )
#define WDG_66_IA_REG_BIT_MCWDT_INTR_ENABLE          ( 0x00000001U )
#define WDG_66_IA_REG_BIT_MCWDT_INTR_DISABLE         ( 0x00000000U )
#define WDG_66_IA_REG_BIT_MCWDT_INTR_MASKED          ( 0x00000001U )

/*==================[type definitions]=======================================*/
/*==================[external function declarations]=========================*/
/*==================[internal function declarations]=========================*/
/*==================[external constants]=====================================*/
/*==================[internal constants]=====================================*/
/*==================[external data]==========================================*/
/*==================[internal data]==========================================*/
/*==================[external function definitions]==========================*/
/*==================[internal function definitions]==========================*/

#endif /* if !defined( WDG_66_IA_HWACCESS_H ) */
/*==================[end of file]============================================*/
