#ifndef PORT_CHECK_PARAMETER_H
#define PORT_CHECK_PARAMETER_H

/** \brief AUTOSAR Port Port Driver
 **
 ** This file define interface of error check function depend on hardware.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */

/*==================[inclusions]=============================================*/
#include <Port_Common_Defines.h> /* PORT driver defines of depend on derivate */
#include <Port_Common_Types.h>   /* PORT driver types */

/*==================[macros]=================================================*/
/*==================[type definitions]=======================================*/
/*==================[external function declarations]=========================*/
#define PORT_START_SEC_CODE_ASIL_B
#include <Port_MemMap.h>

/** \brief Port_Der_IsPortModeValid() check output mode
 **
 ** This function check output Mode.
 **
 ** \param[in]  portPin    Id of PortPin
 ** \param[in]  mode       mode of output
 ** \return result of check PORT_TRUE : OK / PORT_FALSE : NG
 ** */
extern FUNC(boolean,PORT_CODE) Port_Der_IsPortModeValid
(
    Port_PinType     portPin,
    Port_PinModeType mode
);

/** \brief Port_Der_IsInputTriggerValid() check input trigger number
 **
 ** This function checks input trigger number.
 **
 ** \param[in]  group_id  Trigger group ID number
 ** \param[in]  in_trg    Input trigger ID number
 ** \return result of check. PORT_TRUE : OK / PORT_FALSE : NG
 ** */
extern FUNC(boolean,PORT_CODE) Port_Der_IsInputTriggerValid
(
    Port_TriggerGroupIdType group_id,
    Port_TriggerIdType      in_trg
);

/** \brief Port_Der_IsOutputTriggerValid() check output trigger number
 **
 ** This function checks output trigger number.
 **
 ** \param[in]  group_id  Trigger group ID number
 ** \param[in]  out_trg   Output trigger ID number
 ** \return result of check. PORT_TRUE : OK / PORT_FALSE : NG
 ** */
extern FUNC(boolean,PORT_CODE) Port_Der_IsOutputTriggerValid
(
    Port_TriggerGroupIdType group_id,
    Port_TriggerIdType      out_trg
);

/** \brief Port_Der_IsTriggerGroupValid() check trigger group number
 **
 ** This function checks trigger group number.
 **
 ** \param[in]  group_id  Trigger group ID number
 ** \return result of check. PORT_TRUE : OK / PORT_FALSE : NG
 ** */
extern FUNC(boolean,PORT_CODE) Port_Der_IsTriggerGroupValid
(
    Port_TriggerGroupIdType group_id
);

/** \brief Port_Der_IsTriggerManipulationLogic() check trigger manipulation logic
 **
 ** This function checks the presence of trigger manipulation logic.
 **
 ** \param[in]  group_id        Trigger group ID number
 ** \param[in]  inv_flg         Trigger Invert Flag
 ** \param[in]  sensitive_type  Trigger Sensitive Type
 ** \return result of check. PORT_TRUE : OK / PORT_FALSE : NG
 ** */
extern FUNC(boolean,PORT_CODE) Port_Der_IsTriggerManipulationLogic
(
    Port_TriggerGroupIdType     group_id,
    boolean                     inv_flg,
    Port_TriggerSensitiveType   sensitive_type
);

#define PORT_STOP_SEC_CODE_ASIL_B
#include <Port_MemMap.h>

/*==================[internal function declarations]=========================*/
/*==================[external constants]=====================================*/
/*==================[internal constants]=====================================*/
/*==================[external data]==========================================*/
/*==================[internal data]==========================================*/
/*==================[external function definitions]==========================*/
/*==================[internal function definitions]==========================*/

#endif /* PORT_CHECK_PARAMETER_H  */
/*==================[end of file]============================================*/
