/** \brief Lin_Sleep_Li.c
 **
 ** Library-interface: sleep interface.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */

/*==================[inclusions]============================================*/
#include "Lin_LIf_State_Ncp.h"
#include "Lin_LIf_State_Li.h"
#include "Lin_LIf_Common_Ncp.h"
#include "Lin_LIf_Common_Cp.h"
#include "Lin_Li_State_Li.h"

#include "Lin_LIf_Sleep_Li.h"

/*==================[macros]================================================*/

/*==================[type definitions]======================================*/

/*==================[internal function declarations]========================*/

/*==================[internal constants]====================================*/

/*==================[internal data]=========================================*/

/*==================[external function definitions]=========================*/


#define LIN_START_SEC_CODE_ASIL_B
#include "Lin_MemMap.h"

/** \brief Lin_Wakeup_Internal
 **
 ** Internal function: generates a wake up pulse.
 **
 ** \param [in] ChannelIndex   channel index.
 **
 */
FUNC(void, AUTOMATIC) Lin_Wakeup_Internal
(
  VAR(uint8, AUTOMATIC) ChannelIndex
){
    P2VAR(Lin_VarChType, AUTOMATIC, AUTOMATIC) Lin_VarChPtr = Lin_VarChGet( ChannelIndex );
    volatile P2VAR(Lin_LinRegType, AUTOMATIC, AUTOMATIC) LinHwChannelBaseAddressPtr;

    LinHwChannelBaseAddressPtr = Lin_ConstChGetLinBaseAdress_Internal(ChannelIndex);

    /* set variables */
    Lin_VarChPtr -> Lin_ch_stimulation = LIN_INTERNAL_WAKEUP_API;

    /* restart LIN Channel */
    LinHwChannelBaseAddressPtr -> CTL0 = LIN_REG_CTL0_TXWAKE_SET;

    /* set TX_WAKEUP and other command clear */
    LinHwChannelBaseAddressPtr -> CMD = LIN_REG_CMD_TX_WAKE_SET;
}

/** \brief Lin_WakeupInternal_Internal
 **
 ** Internal function: Only state transition without generates a wake up pulse.
 **
 ** \param [in] ChannelIndex   channel index.
 **
 */
FUNC(void, AUTOMATIC) Lin_WakeupInternal_Internal
(
  VAR(uint8, AUTOMATIC) ChannelIndex
){
    P2VAR(Lin_VarChType, AUTOMATIC, AUTOMATIC) Lin_VarChPtr = Lin_VarChGet( ChannelIndex );

    /* set variables */
    Lin_VarChPtr -> Lin_ch_stimulation = LIN_INTERNAL_WAKEUPINTERNAL_API;
}

#define LIN_STOP_SEC_CODE_ASIL_B
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1
   Justification: MemMap.h must be included in-line. */
/* PRQA S 5087 1 */
#include "Lin_MemMap.h"

/*==================[end of file]===========================================*/
