/** \brief Lin_LIf_Status.h
 **
 ** Library-interface: status interface defines.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */

#ifndef LIN_LIF_STATUS_H_INCLUDED
#define LIN_LIF_STATUS_H_INCLUDED

/*==================[inclusions]============================================*/


/*==================[macros]================================================*/

#if (defined LIN_MODULE_ID) /* to prevent double declaration */
#error LIN_MODULE_ID already defined
#endif /* if (defined LIN_MODULE_ID) */

/** ASR LIN module ID. */
#define LIN_MODULE_ID 82U

#if (defined LIN_VENDOR_ID) /* to prevent double declaration */
#error LIN_VENDOR_ID already defined
#endif /* if (defined LIN_VENDOR_ID) */

/** ASR vendor ID. */
#define LIN_VENDOR_ID 66U

/*------------------[AUTOSAR specification version identification]----------*/

#if (defined LIN_AR_RELEASE_MAJOR_VERSION) /* to prevent double declaration */
#error LIN_AR_RELEASE_MAJOR_VERSION already defined
#endif /* if (defined LIN_AR_RELEASE_MAJOR_VERSION) */

/** Driver ASR major version. */
#define LIN_AR_RELEASE_MAJOR_VERSION 4U

#if (defined LIN_AR_RELEASE_MINOR_VERSION) /* to prevent double declaration */
#error LIN_AR_RELEASE_MINOR_VERSION already defined
#endif /* if (defined LIN_AR_RELEASE_MINOR_VERSION) */

/** Driver ASR minor version. */
#define LIN_AR_RELEASE_MINOR_VERSION 2U

#if (defined LIN_AR_RELEASE_REVISION_VERSION) /* to prevent double declaration */
#error LIN_AR_RELEASE_REVISION_VERSION already defined
#endif /* if (defined LIN_AR_RELEASE_REVISION_VERSION) */

/** Driver ASR revision version. */
#define LIN_AR_RELEASE_REVISION_VERSION 2U

/*------------------[Cypress module version identification]----------------*/

#if (defined LIN_SW_MAJOR_VERSION) /* to prevent double declaration */
#error LIN_SW_MAJOR_VERSION already defined
#endif /* if (defined LIN_SW_MAJOR_VERSION) */

/** Driver SW major version. */
#define LIN_SW_MAJOR_VERSION 1U


#if (defined LIN_SW_MINOR_VERSION) /* to prevent double declaration */
#error LIN_SW_MINOR_VERSION already defined
#endif /* if (defined LIN_SW_MINOR_VERSION) */

/** Driver SW minor version. */
#define LIN_SW_MINOR_VERSION 11U


/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

/*==================[end of file]===========================================*/

#endif /*!defined(LIN_LIF_STATUS_H_INCLUDED)*/
