/** \brief Lin_Operational_Ncp.c
 **
 ** Configuration dependent operational interface.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */

/*==================[inclusions]============================================*/
#include "Lin_LIf_State_Ncp.h"
#include "Lin_LIf_State_Li.h"
#include "Lin_LIf_Status_Li.h"
#include "Lin_LIf_Operational_Li.h"
#include "Lin_LIf_Common_Ncp.h"
#include "Lin_LIf_Common_Cp.h"
#include "Lin_LIf_Common_Li.h"
#include "Lin_Defines.h"
#include "Lin_Ncp_Common.h"

#include "Lin_Ncp_Operational_Ncp.h"

/*==================[macros]================================================*/

/*==================[type definitions]======================================*/

/*==================[internal function declarations]========================*/

/*==================[external function definitions]=========================*/

#define LIN_START_SEC_CODE_ASIL_B
#include "Lin_MemMap.h"

/** \brief Lin_GoToSleep
 **
 ** The service instructs the driver to transmit a go-to-sleep-command on the
 ** addressed LIN channel.
 **
 ** \return Acceptance status of sleep command: E_OK or E_NOT_OK
 ** \param [in] Channel   channel id
 **
 */
FUNC(Std_ReturnType, AUTOMATIC) Lin_GoToSleep
(
  VAR(uint8, AUTOMATIC) Channel
){
    uint8 ChannelIndex = Lin_GetChannelIndex ( Channel );
    boolean DetsPassed = TRUE;
    Std_ReturnType Std_Return = E_NOT_OK;
    Lin_VarCh_StatusType Lin_VarCh_Status;
    
    if ( Lin_Var_ModuleStatusGet( ) != LIN_STATUS_MOD_INIT ){
      Lin_ErrorWrapper( LIN_GOTOSLEEP_API_ID, LIN_E_UNINIT );
      DetsPassed = FALSE;
    }

    if ( ChannelIndex >= LIN_NUMBER_OF_CONFIGURED_CHANNELS ){
      Lin_ErrorWrapper( LIN_GOTOSLEEP_API_ID, LIN_E_INVALID_CHANNEL );
      DetsPassed = FALSE;
    }

    if ( DetsPassed == TRUE ){
      Lin_VarCh_Status = Lin_GetStatus_Internal( ChannelIndex );
      Std_Return = E_OK;
      if ( (Lin_VarCh_Status != LIN_INTERNAL_CH_SLEEP) && 
           (Lin_VarCh_Status != LIN_INTERNAL_CH_SLEEP_PENDING) ){
        /* stop and reset HW, disable interupts, clear flags */
        Lin_StopHwOperation_Internal( ChannelIndex );
        /* enable gotosleep completion interrupt. */
        Lin_EnableTxInterrupt_Internal( ChannelIndex );
        Lin_GoToSleep_Internal( ChannelIndex );
      }
    }
    return Std_Return;
}

/** \brief Lin_GoToSleepInternal
 **
 ** Sets the channel state to LIN_CH_SLEEP, enables the wake-up detection and
 ** optionally sets the LIN hardware unit.
 **
 ** \return Acceptance status of sleep command: E_OK or E_NOT_OK
 ** \param [in] Channel   channel id
 **
 */
FUNC(Std_ReturnType, AUTOMATIC) Lin_GoToSleepInternal
(
  VAR(uint8, AUTOMATIC) Channel
){
    uint8 ChannelIndex = Lin_GetChannelIndex ( Channel );
    boolean DetsPassed = TRUE;
    Std_ReturnType Std_Return = E_NOT_OK;

    if ( Lin_Var_ModuleStatusGet( ) != LIN_STATUS_MOD_INIT ){
      Lin_ErrorWrapper( LIN_GOTOSLEEPINTERNAL_API_ID, LIN_E_UNINIT );
      DetsPassed = FALSE;
    }

    if ( ChannelIndex >= LIN_NUMBER_OF_CONFIGURED_CHANNELS ){
      Lin_ErrorWrapper( LIN_GOTOSLEEPINTERNAL_API_ID, LIN_E_INVALID_CHANNEL );
      DetsPassed = FALSE;
    }

    if ( DetsPassed == TRUE ){
        Lin_GoToSleepInternal_Internal( ChannelIndex );
        /* enable wakeup-by-LinBusSlave interrupt. */
        Lin_EnableRxInterrupt_Internal( ChannelIndex );
        Std_Return = E_OK;
    }
    return Std_Return;
}

/** \brief Lin_SendFrame
 **
 ** Sends a LIN header and a LIN response, if necessary. The direction of the frame
 ** response (master response, slave response, slave-to-slave communication) is
 ** provided by the PduInfoPtr.
 **
 ** \return Acceptance status of send command: E_OK or E_NOT_OK
 ** \param [in] Channel   channel id
 ** \param [inout] PduInfoPtr   pointer to pdu
 **
 */
FUNC(Std_ReturnType, AUTOMATIC) Lin_SendFrame
(
  VAR(uint8, AUTOMATIC) Channel,
  P2VAR(Lin_PduType, AUTOMATIC, AUTOMATIC) PduInfoPtr
){
    uint8 ChannelIndex = Lin_GetChannelIndex ( Channel );
    boolean DetsPassed = TRUE;
    Std_ReturnType Std_Return = E_NOT_OK;
    Lin_VarCh_PduType Lin_VarCh_Pdu;

    if ( Lin_Var_ModuleStatusGet( ) != LIN_STATUS_MOD_INIT ){
      Lin_ErrorWrapper( LIN_SENDFRAME_API_ID, LIN_E_UNINIT );
      DetsPassed = FALSE;
    }

    if ( PduInfoPtr == NULL_PTR ){
      Lin_ErrorWrapper( LIN_SENDFRAME_API_ID, LIN_E_PARAM_POINTER );
      DetsPassed = FALSE;
    } else {
      if (!( ( PduInfoPtr -> Pid <= 0xFEU ) && 
             ( ( PduInfoPtr -> Cs == LIN_CLASSIC_CS ) || 
               ( PduInfoPtr -> Cs == LIN_ENHANCED_CS ) ) && 
             ( ( PduInfoPtr -> Drc == LIN_MASTER_RESPONSE ) || 
               ( PduInfoPtr -> Drc == LIN_SLAVE_RESPONSE ) || 
               ( PduInfoPtr -> Drc == LIN_SLAVE_TO_SLAVE ) ) && 
             ( PduInfoPtr -> Dl != 0U ) &&                
             ( PduInfoPtr -> Dl <= 8U ) && 
             ( PduInfoPtr -> SduPtr != NULL_PTR ) ) ){
        Lin_ErrorWrapper( LIN_SENDFRAME_API_ID, LIN_E_PARAM_POINTERCONTENT );
        DetsPassed = FALSE;
      }
    }

    if ( ChannelIndex >= LIN_NUMBER_OF_CONFIGURED_CHANNELS ){
      Lin_ErrorWrapper( LIN_SENDFRAME_API_ID, LIN_E_INVALID_CHANNEL );
      DetsPassed = FALSE;
    }

    if ( DetsPassed == TRUE ){
      if ( Lin_GetStatus_Internal( ChannelIndex ) == LIN_INTERNAL_CH_SLEEP ){
        Lin_ErrorWrapper( LIN_SENDFRAME_API_ID, LIN_E_STATE_TRANSITION );
      } else {
        /* stop and reset HW, disable interrupts, clear flags */
        Lin_StopHwOperation_Internal( ChannelIndex );
        Lin_VarCh_Pdu.Pid = PduInfoPtr -> Pid;
        switch( PduInfoPtr -> Cs ){
          case LIN_ENHANCED_CS:
            Lin_VarCh_Pdu.Cs = LIN_INTERNAL_ENHANCED_CS;
            break;
          default:/*include LIN_CLASSIC_CS*/
            Lin_VarCh_Pdu.Cs = LIN_INTERNAL_CLASSIC_CS;
            break;
        }
        switch( PduInfoPtr -> Drc ){
          case LIN_MASTER_RESPONSE:
            Lin_VarCh_Pdu.Drc = LIN_INTERNAL_MASTER_RESPONSE;
            break;
          case LIN_SLAVE_RESPONSE:
            Lin_VarCh_Pdu.Drc = LIN_INTERNAL_SLAVE_RESPONSE;
            break;
          default:/*include LIN_SLAVE_TO_SLAVE*/
            Lin_VarCh_Pdu.Drc = LIN_INTERNAL_SLAVE_TO_SLAVE;
            break;
        }
        Lin_VarCh_Pdu.Dl = PduInfoPtr -> Dl;
        Lin_VarCh_Pdu.SduPtr = PduInfoPtr -> SduPtr;
        Lin_SendFrame_Internal( ChannelIndex, &Lin_VarCh_Pdu);
        Std_Return = E_OK;
      }
    }
    return Std_Return;
}

#define LIN_STOP_SEC_CODE_ASIL_B
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1
   Justification: MemMap.h must be included in-line. */
/* PRQA S 5087 1 */
#include "Lin_MemMap.h"

/*==================[end of file]===========================================*/
