/** \brief Lin_Common_Ncp.c
 **
 ** Library-interface: common interface Ncp.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */

/*==================[inclusions]============================================*/
#include "Lin_Defines.h"
#include "Lin_Ncp_Common.h"
#include "Lin_LIf_Status.h"

#if (LIN_DEV_ERROR_DETECT == STD_ON)
#include <Det.h>
#endif /* #if (LIN_DEV_ERROR_DETECT == STD_ON) */

#include <EcuM.h>
#include <EcuM_Cbk.h>

#include <LinIf_Cbk.h>

#include "Lin_LIf_Common_Ncp.h"

/*==================[macros]================================================*/

/*==================[type definitions]======================================*/

/*==================[internal function declarations]========================*/

/*==================[internal constants]====================================*/

#define LIN_START_SEC_CONST_ASIL_B_UNSPECIFIED
#include "Lin_MemMap.h"

static CONST(Lin_ConstChType, AUTOMATIC) Lin_ConstCh[LIN_NUMBER_OF_CONFIGURED_CHANNELS] = LIN_CONSTCH_CFG_ITEMS;
/* Deviation from MISRA-C:2004 rule 8.7, MISRA-C:2012 Rule-8.9
   Justification: Allow memory mapping (MemMap). */
/* PRQA S 3218 1 */
static CONST(Lin_ConstType, AUTOMATIC) Lin_Const = LIN_CONST_CFG_ITEMS;

#define LIN_STOP_SEC_CONST_ASIL_B_UNSPECIFIED
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1
   Justification: MemMap.h must be included in-line. */
/* PRQA S 5087 1 */
#include "Lin_MemMap.h"

/*==================[external function definitions]=========================*/

#define LIN_START_SEC_CODE_ASIL_B
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1
   Justification: MemMap.h must be included in-line. */
/* PRQA S 5087 1 */
#include "Lin_MemMap.h"

/** \brief Lin_ConstChGet
 **
 ** Internal function: obtain channel specific constants.
 **
 ** \return channel specific constants.
 ** \param [in] ChannelIndex   channel index.
 **
 */
FUNC_P2CONST(Lin_ConstChType, AUTOMATIC, AUTOMATIC) Lin_ConstChGet
(
  VAR(uint8, AUTOMATIC) ChannelIndex
){
    return (&Lin_ConstCh[ChannelIndex]);
}

/** \brief Lin_ConstGet
 **
 ** Internal function: obtain module specific constants.
 **
 ** \return module constants.
 **
 */
FUNC_P2CONST(Lin_ConstType, AUTOMATIC, AUTOMATIC) Lin_ConstGet
(
  void
){
    return (&Lin_Const);
}

/** \brief Lin_ErrorWrapper
 **
 ** Internal function: wrapper function to call DET module function and the error
 ** callout handler.
 **
 ** \param [in] ApiId   API ID
 ** \param [in] ErrorId   Error ID
 **
 */
FUNC(void, AUTOMATIC) Lin_ErrorWrapper
(
  VAR(uint8, AUTOMATIC) ApiId,
  VAR(uint8, AUTOMATIC) ErrorId
){
    /* ASIL error callout. */
    LIN_ERROR_CALLOUT_FUNCTION(LIN_MODULE_ID, LIN_INDEX, ApiId, ErrorId);

#if (LIN_DEV_ERROR_DETECT == STD_ON)
    (void)Det_ReportError(LIN_MODULE_ID, LIN_INDEX, ApiId, ErrorId);
#endif /* #if (LIN_DEV_ERROR_DETECT == STD_ON) */
}

/** \brief Lin_EcuMSetWakeupEventWrapper
 **
 ** Internal function: wrapper function to call EcuM module function.
 **
 ** \param [in] ChannelIndex   channel index
 **
 */
FUNC(void, AUTOMATIC) Lin_EcuMSetWakeupEventWrapper
(
  VAR(uint8, AUTOMATIC) ChannelIndex
){
    /* check if specific channel supports wakeup */
    if ( ( (&Lin_ConstCh[ChannelIndex]) -> LinChannelWakeupSupport ) == TRUE ){
      EcuM_SetWakeupEvent ( (&Lin_ConstCh[ChannelIndex]) -> LinChannelEcuMWakeupSource);
    }
}

/** \brief Lin_EcuMCheckWakeupWrapper
 **
 ** Internal function: wrapper function to call EcuM module function.
 **
 ** \param [in] ChannelIndex   channel index
 **
 */
FUNC(void, AUTOMATIC) Lin_EcuMCheckWakeupWrapper
(
  VAR(uint8, AUTOMATIC) ChannelIndex
){
    /* check if specific channel supports wakeup */
    if ( (( &Lin_ConstCh[ChannelIndex]) -> LinChannelWakeupSupport ) == TRUE ){
      EcuM_CheckWakeup ( (&Lin_ConstCh[ChannelIndex]) -> LinChannelEcuMWakeupSource );
    }
}

/** \brief Lin_LinIfWakeupConfirmationWrapper
 **
 ** Internal function: wrapper function to call LinIf module function.
 **
 ** \param [in] ChannelIndex   channel index
 **
 */
FUNC(void, AUTOMATIC) Lin_LinIfWakeupConfirmationWrapper
(
  VAR(uint8, AUTOMATIC) ChannelIndex
){
    /* check if specific channel supports wakeup */
    if ( ( (&Lin_ConstCh[ChannelIndex]) -> LinChannelWakeupSupport ) == TRUE ){
      LinIf_WakeupConfirmation ( (&Lin_ConstCh[ChannelIndex]) -> LinChannelEcuMWakeupSource);
    }
}

#define LIN_STOP_SEC_CODE_ASIL_B
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1
   Justification: MemMap.h must be included in-line. */
/* PRQA S 5087 1 */
#include "Lin_MemMap.h"

/*==================[end of file]===========================================*/
