/** \file Icu_Channel_EdgeCount.c
 **
 ** This file contains edge count mode internal architecture function
 ** for the AUTOSAR Icu driver.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */
/*==================[inclusions]=============================================*/
#include <Icu_Channel_EdgeCount.h>
#include <Icu_Internal.h>
#include <Icu_Resource.h>

/*==================[external function definitions]=========================*/
#define ICU_START_SEC_CODE_ASIL_B
#include <Icu_MemMap.h>

/** \brief Icu_EnableEdgeCount_Internal
 **
 ** This function enables the edge count.
 **
 ** \param[in]  ChannelPtr      Pointer to the channel configuration.
 ** \param[in]  ChannelCtrl     Control the channel start or no start.
 ** 
 ** \return    None.
 ** */
FUNC(void, ICU_CODE) Icu_EnableEdgeCount_Internal
(
  P2CONST(Icu_ChannelConfigType, AUTOMATIC, ICU_APPL_CONST) ChannelPtr,
  VAR(Icu_ChannelCtrlType, AUTOMATIC)                       ChannelCtrl
)
{
  P2CONST(Icu_drvFctTable_t,     AUTOMATIC, ICU_APPL_CONST) FuncTablePtr = (*ChannelPtr->GetFuncTable)();

  Icu_EnterCritiSec();

  FuncTablePtr->drvClearInterruptRequestFlag(ChannelPtr, ICU_MASK_INTR_MASK_CC0_MATCH);
  FuncTablePtr->drvIsrEnable(ChannelPtr, ICU_MASK_INTR_MASK_CC0_MATCH);
  /* Check if start channel by software trigger */
  if (ChannelCtrl == ICU_CHSTART)
  {
    /* Start trigger */
    FuncTablePtr->drvStartCountTrigger(ChannelPtr);
  }
  /* Set running status */
  ChannelPtr->StatePtr->Status = ICU_RUNNING;

  Icu_ExitCritiSec();
}

/** \brief Icu_DisableEdgeCount_Internal
 **
 ** The function disables the edge count.
 **
 ** \param[in]  ChannelPtr      Pointer to the channel configuration.
 ** \param[in]  ChannelCtrl     Control the channel stop or no stop.
 ** 
 ** \return    None.
 ** */
FUNC(void, ICU_CODE) Icu_DisableEdgeCount_Internal
(
  P2CONST(Icu_ChannelConfigType, AUTOMATIC, ICU_APPL_CONST) ChannelPtr,
  VAR(Icu_ChannelCtrlType, AUTOMATIC)                       ChannelCtrl
)
{
  P2CONST(Icu_drvFctTable_t,     AUTOMATIC, ICU_APPL_CONST) FuncTablePtr = (*ChannelPtr->GetFuncTable)();

  Icu_EnterCritiSec();
  /* Check if stop channel by software trigger */
  if (ChannelCtrl == ICU_CHSTOP)
  {
    FuncTablePtr->drvCtrlEnable(ChannelPtr, FALSE);
    /* Clear input trigger */
    FuncTablePtr->drvClearInputTrigger(ChannelPtr);
    FuncTablePtr->drvCtrlEnable(ChannelPtr, TRUE);
  }
  /* Disable interrupt */
  FuncTablePtr->drvIsrDisable(ChannelPtr, ICU_MASK_INTR_MASK_CC0_MATCH);
  ChannelPtr->StatePtr->Status = ICU_STOPPED;

  Icu_ExitCritiSec();
}

/** \brief Icu_GetEdgeNumbers_Internal
 **
 ** The function gets the edge count.
 **
 ** \param[in]  ChannelPtr      Pointer to the channel configuration.
 ** 
 ** \return     Return the number of counted edges.
 ** */
FUNC(Icu_EdgeNumberType, ICU_CODE) Icu_GetEdgeNumbers_Internal
(
  P2CONST(Icu_ChannelConfigType, AUTOMATIC, ICU_APPL_CONST) ChannelPtr
)
{
  Icu_EdgeNumberType EdgeNum;
  P2VAR(Icu_EdgeCountChannelStateType, AUTOMATIC, ICU_APPL_DATA) ChExtStatePtr;
  /* Deviation from MISRA-C:2004 rule 11.4, MISRA-C:2012 Rule-11.5
     Justification: It is a necessary for Extension State access. */
  /* PRQA S 316 1 */
  ChExtStatePtr = (P2VAR(Icu_EdgeCountChannelStateType, AUTOMATIC, ICU_APPL_DATA)) ChannelPtr->ExtStatePtr;

  /* Get edge number */
  EdgeNum = ChExtStatePtr->EdgeNumber;

  return EdgeNum;
  
}

/** \brief Icu_EdgeCount_InterruptEvent
 **
 ** This function is the ISR of edge count mode.
 **
 ** \param[in] ChannelPtr      Pointer to the channel configuration.
 ** \param[in] IntrFlag        Interrupt request flag of channel.
 ** 
 ** \return    None.
 ** */
FUNC(void, ICU_CODE) Icu_EdgeCount_InterruptEvent
(
  P2CONST(Icu_ChannelConfigType, AUTOMATIC, ICU_APPL_CONST) ChannelPtr,
  VAR(uint8, AUTOMATIC)                                     IntrFlag
)
{
  P2VAR(Icu_EdgeCountChannelStateType, AUTOMATIC, ICU_APPL_DATA) ChExtStatePtr;
  /* Deviation from MISRA-C:2004 rule 11.4, MISRA-C:2012 Rule-11.5
     Justification: It is a necessary for Extension State access. */
  /* PRQA S 316 1 */
  ChExtStatePtr = (P2VAR(Icu_EdgeCountChannelStateType, AUTOMATIC, ICU_APPL_DATA)) ChannelPtr->ExtStatePtr;
  /* Check if valid interrupt is detected */
  if ((0U != (ICU_INT_CAPTURE & IntrFlag)) && (ICU_RUNNING == ChannelPtr->StatePtr->Status))
  {
    /* Count value increase */
    ChExtStatePtr->EdgeNumber++;

  }
}

#define ICU_STOP_SEC_CODE_ASIL_B
/* Deviation from MISRA-C:2004 rule 19.1, MISRA-C:2012 Rule-20.1
   Justification: This implementation is specified by AUTOSAR specification. */
/* PRQA S 5087 1 */
#include <Icu_MemMap.h>
/*==================[end of file]============================================*/
