#ifndef PORT_VERSION_H
#define PORT_VERSION_H

/** \brief AUTOSAR Port Port Driver
 **
 ** This file contains the declaration of the version of the
 ** AUTOSAR module Port.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */

/*==================[inclusions]=============================================*/
#include <Port_Cfg.h>            /* PORT driver configuration sybolic defines */

/*==================[macros]=================================================*/
/*------------------[AUTOSAR specification version]--------------------------*/
/* to prevent double declaration */
#if (defined PORT_AR_RELEASE_MAJOR_VERSION)
#error PORT_AR_RELEASE_MAJOR_VERSION already defined
#endif /* if (defined PORT_AR_RELEASE_MAJOR_VERSION) */

/** \brief AUTOSAR major version */
#define PORT_AR_RELEASE_MAJOR_VERSION    4U

/* to prevent double declaration */
#if (defined PORT_AR_RELEASE_MINOR_VERSION)
#error PORT_AR_RELEASE_MINOR_VERSION already defined
#endif /* if (defined PORT_AR_RELEASE_MINOR_VERSION) */

/** \brief AUTOSAR minor version */
#define PORT_AR_RELEASE_MINOR_VERSION    2U

/* to prevent double declaration */
#if (defined PORT_AR_RELEASE_REVISION_VERSION)
#error PORT_AR_RELEASE_REVISION_VERSION already defined
#endif /* if (defined PORT_AR_RELEASE_REVISION_VERSION) */

/** \brief AUTOSAR revision version */
#define PORT_AR_RELEASE_REVISION_VERSION 2U

/*------------------[AUTOSAR module version identification]------------------*/
/* to prevent double declaration */
#if (defined PORT_SW_MAJOR_VERSION)
#error PORT_SW_MAJOR_VERSION already defined
#endif /* if (defined PORT_SW_MAJOR_VERSION) */

/** \brief Software major version */
#define PORT_SW_MAJOR_VERSION  1U

/* to prevent double declaration */
#if (defined PORT_SW_MINOR_VERSION)
#error PORT_SW_MINOR_VERSION already defined
#endif /* if (defined PORT_SW_MINOR_VERSION) */

/** \brief Software minor version */
#define PORT_SW_MINOR_VERSION  18U

/* to prevent double declaration */
#if (defined PORT_SW_PATCH_VERSION)
#error PORT_SW_PATCH_VERSION already defined
#endif /* if (defined PORT_SW_PATCH_VERSION) */

/** \brief Software patch version */
#define PORT_SW_PATCH_VERSION  PORT_GEN_SW_PATCH_VERSION


/**
 * Macro for checking the consistency of AUTOSAR Spec versions of the
 * different files of the <MODULE> module
 */
/* Deviation from MISRA-C:2004 rule 19.7, MISRA-C:2012 Dir-4.9
   Justification: Implementation often uses macro like function. */
/* PRQA S 3453 10 */
#define PORT_AR_VERSION_CHECK(                                             \
    file_ar_major_version,                                                 \
    file_ar_minor_version,                                                 \
    file_ar_patch_version                                                  \
    )                                                                      \
    (                                                                      \
        ((PORT_AR_RELEASE_MAJOR_VERSION)    == (file_ar_major_version)) && \
        ((PORT_AR_RELEASE_MINOR_VERSION)    == (file_ar_minor_version)) && \
        ((PORT_AR_RELEASE_REVISION_VERSION) == (file_ar_patch_version))    \
    )

/**
 * Macro for checking the consistency of the software versions of the
 * different files of the Port module
 */
/* Deviation from MISRA-C:2004 rule 19.7, MISRA-C:2012 Dir-4.9
   Justification: Implementation often uses macro like function. */
/* PRQA S 3453 10 */
#define PORT_SW_VERSION_CHECK(                                  \
    file_sw_major_version,                                      \
    file_sw_minor_version,                                      \
    file_sw_patch_version                                       \
    )                                                           \
    (                                                           \
        ((PORT_SW_MAJOR_VERSION) == (file_sw_major_version)) && \
        ((PORT_SW_MINOR_VERSION) == (file_sw_minor_version)) && \
        ((PORT_SW_PATCH_VERSION) >= 0)                          \
    )


/*==================[type definitions]=======================================*/
/*==================[external function declarations]=========================*/
/*==================[internal function declarations]=========================*/
/*==================[external constants]=====================================*/
/*==================[internal constants]=====================================*/
/*==================[external data]==========================================*/
/*==================[internal data]==========================================*/
/*==================[external function definitions]==========================*/
/*==================[internal function definitions]==========================*/

#endif /* PORT_VERSION_H  */
/*==================[end of file]============================================*/
