/** \brief Lin_Ncp_Operational_Ncp.h
 **
 ** Configuration dependent operational interface.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */

#ifndef LIN_NCP_OPERATIONAL_NCP_H_INCLUDED
#define LIN_NCP_OPERATIONAL_NCP_H_INCLUDED

/*==================[inclusions]============================================*/
#include <Std_Types.h>
#include <Lin_GeneralTypes.h>

/*==================[macros]================================================*/

/*==================[type definitions]======================================*/

/*==================[external function declarations]========================*/

#define LIN_START_SEC_CODE_ASIL_B
#include "Lin_MemMap.h"

/** \brief Lin_GoToSleep
 **
 ** The service instructs the driver to transmit a go-to-sleep-command on the
 ** addressed LIN channel.
 **
 ** \return Acceptance status of sleep command: E_OK or E_NOT_OK
 ** \param [in] Channel   channel id
 **
 */
extern FUNC(Std_ReturnType, AUTOMATIC) Lin_GoToSleep
(
  VAR(uint8, AUTOMATIC) Channel
);

/** \brief Lin_GoToSleepInternal
 **
 ** Sets the channel state to LIN_CH_SLEEP, enables the wake-up detection and
 ** optionally sets the LIN hardware unit.
 **
 ** \return Acceptance status of sleep command: E_OK or E_NOT_OK
 ** \param [in] Channel   channel id
 **
 */
extern FUNC(Std_ReturnType, AUTOMATIC) Lin_GoToSleepInternal
(
  VAR(uint8, AUTOMATIC) Channel
);

/** \brief Lin_SendFrame
 **
 ** Sends a LIN header and a LIN response, if necessary. The direction of the frame
 ** response (master response, slave response, slave-to-slave communication) is
 ** provided by the PduInfoPtr.
 **
 ** \return Acceptance status of send command: E_OK or E_NOT_OK
 ** \param [in] Channel   channel id
 ** \param [inout] PduInfoPtr   pointer to pdu
 **
 */
extern FUNC(Std_ReturnType, AUTOMATIC) Lin_SendFrame
(
  VAR(uint8, AUTOMATIC) Channel,
  P2VAR(Lin_PduType, AUTOMATIC, AUTOMATIC) PduInfoPtr
);

#define LIN_STOP_SEC_CODE_ASIL_B
#include "Lin_MemMap.h"

/*==================[end of file]===========================================*/

#endif /*!defined(LIN_NCP_OPERATIONAL_NCP_H_INCLUDED)*/
