
#ifndef WDG_H
#define WDG_H 1

/** \brief AUTOSAR Wdg Driver
 **
 ** This file contains or includes all external identifiers of the AUTOSAR
 ** module Wdg.
 ** If only one watchdog module is used within the ASC this header might be
 ** used instead of the default WDG_66_IA.h header for accessing the watchdog
 ** hardware.
 **
 ** Do not edit this file manually.
 ** Any change might compromise the safety integrity level of
 ** the software partition it is contained in.
 **
 ** Product: SW-MCAL42-DRV
 **
 ** (c) 2017-2022, Cypress Semiconductor Corporation (an Infineon company) or
 ** an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
 ** This software, including source code, documentation and related materials
 ** ("Software") is owned by Cypress Semiconductor Corporation or one of
 ** its affiliates ("Cypress") and is protected by and subject to worldwide
 ** patent protection (United States and foreign), United States copyright laws
 ** and international treaty provisions.  Therefore, you may use this Software
 ** only as provided in the license agreement accompanying the software package
 ** from which you obtained this Software ("EULA").
 ** If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 ** non-transferable license to copy, modify,
 ** and compile the Software source code solely for use in connection
 ** with Cypress's integrated circuit products.
 ** Any reproduction, modification, translation, compilation,
 ** or representation of this Software except as specified above is prohibited
 ** without the express written permission of Cypress.
 ** Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 ** EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT,
 ** IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 ** Cypress reserves the right to make changes to the Software without notice.
 ** Cypress does not assume any liability arising out of the application or
 ** use of the Software or any product or circuit described in the Software.
 ** Cypress does not authorize its products for use in any products
 ** where a malfunction or failure of the Cypress product may reasonably be
 ** expected to result in significant property damage,
 ** injury or death ("High Risk Product"). By including Cypress's product
 ** in a High Risk Product, the manufacturer of such system or application
 ** assumes all risk of such use and in doing so agrees to indemnify Cypress
 ** against all liability.
 */

/*==================[inclusions]=============================================*/

#include <Wdg_66_IA.h>

/*==================[macros]=================================================*/

/*------------------[Wdg Index Symbolic Names]-------------------------------*/
#define WdgConf_WdgGeneral_WdgGeneral  Wdg_66_IAConf_WdgGeneral_WdgGeneral

/* ------------------[ Versioning & ID's ]----------------------*/

#define WDG_SW_MAJOR_VERSION            WDG_66_IA_SW_MAJOR_VERSION
#define WDG_SW_MINOR_VERSION            WDG_66_IA_SW_MINOR_VERSION
#define WDG_SW_PATCH_VERSION            WDG_66_IA_SW_PATCH_VERSION
#define WDG_AR_RELEASE_MAJOR_VERSION    WDG_66_IA_AR_RELEASE_MAJOR_VERSION
#define WDG_AR_RELEASE_MINOR_VERSION    WDG_66_IA_AR_RELEASE_MINOR_VERSION
#define WDG_AR_RELEASE_REVISION_VERSION WDG_66_IA_AR_RELEASE_REVISION_VERSION

#define WDG_MODULE_ID                   WDG_66_IA_MODULE_ID
#define WDG_VENDOR_ID                   WDG_66_IA_VENDOR_ID
#define WDG_INSTANCE_ID                 WDG_66_IA_INSTANCE_ID
#define WDG_INSTANCE_ID_DET             WDG_66_IA_INSTANCE_ID_DET

/* -------------------[ API's & API ID's ]----------------------*/

#define Wdg_Init                        Wdg_66_IA_Init
#define Wdg_SetMode                     Wdg_66_IA_SetMode
#define Wdg_SetTriggerCondition         Wdg_66_IA_SetTriggerCondition
#define Wdg_GetVersionInfo              Wdg_66_IA_GetVersionInfo

#define WDG_API_INIT                    WDG_66_IA_API_INIT
#define WDG_API_SETMODE                 WDG_66_IA_API_SETMODE
#define WDG_API_SET_TRIGGER_CONDITION   WDG_66_IA_API_SET_TRIGGER_CONDITION
#define WDG_API_GET_VERSION_INFO        WDG_66_IA_API_GET_VERSION_INFO
#define WDG_API_WARNINT                 WDG_66_IA_API_WARNINT

/* -------------------------[ Types ]---------------------------*/

#define Wdg_ConfigType                  Wdg_66_IA_ConfigType
#define Wdg_StatusType                  Wdg_66_IA_StatusType
#define Wdg_SettingCommonType           Wdg_66_IA_SettingCommonType
#define Wdg_SettingType                 Wdg_66_IA_SettingType
#define Wdg_TriggerModeType             Wdg_66_IA_TriggerModeType
#define Wdg_SettingTriggerType          Wdg_66_IA_SettingTriggerType

/* -----------------[ Variables & Constants ]-------------------*/

#define Wdg_Config                      Wdg_66_IA_Config

#define WDG_TRIGGER_LOCATION            WDG_66_IA_TRIGGER_LOCATION
#define WDG_DISABLE_ALLOWED             WDG_66_IA_DISABLE_ALLOWED
#define WDG_CONFIGURATION               WDG_66_IA_CONFIGURATION

/* -----------------------[ Error Codes ]-----------------------*/

#define WDG_E_INIT_FAILED               WDG_66_IA_E_INIT_FAILED
#define WDG_E_DRIVER_STATE              WDG_66_IA_E_DRIVER_STATE
#define WDG_E_PARAM_MODE                WDG_66_IA_E_PARAM_MODE
#define WDG_E_PARAM_CONFIG              WDG_66_IA_E_PARAM_CONFIG
#define WDG_E_PARAM_TIMEOUT             WDG_66_IA_E_PARAM_TIMEOUT
#define WDG_E_PARAM_POINTER             WDG_66_IA_E_PARAM_POINTER
#define WDG_E_EXTENDED_MODE_FAILED      WDG_66_IA_E_EXTENDED_MODE_FAILED
#define WDG_E_EXTENDED_DISABLE_REJECTED WDG_66_IA_E_EXTENDED_DISABLE_REJECTED
#define WDG_E_EXTENDED_HW_TIMEOUT       WDG_66_IA_E_EXTENDED_HW_TIMEOUT
#define WDG_E_EXTENDED_WDG_STOPPED      WDG_66_IA_E_EXTENDED_WDG_STOPPED

/*==================[type definitions]=======================================*/
/*==================[external function declarations]=========================*/
/*==================[internal function declarations]=========================*/
/*==================[external constants]=====================================*/
/*==================[internal constants]=====================================*/
/*==================[external data]==========================================*/
/*==================[internal data]==========================================*/
/*==================[external function definitions]==========================*/
/*==================[internal function definitions]==========================*/

#endif /* ifndef WDG_H */
/*==================[end of file]============================================*/
